### ISSUE TITLE
Support read-only subset of Virtio-FS file system

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1062]
Some resources:
- https://virtio-fs.gitlab.io/index.html#faq 
- https://stefanha.github.io/virtio/virtio-fs.html#x1-41500011 (look for virtio-fs)
- https://virtio-fs.gitlab.io/howto-qemu.html
- https://lists.oasis-open.org/archives/virtio-dev/201812/msg00073.html
 
This would require implementing a new virtio device and a new filesystem. The challenge is that Linux implementation (https://gitlab.com/virtio-fs/linux/blob/virtio-fs/fs/fuse/virtio_fs.c and https://gitlab.com/virtio-fs/linux/blob/virtio-fs/fs/fuse/inode.c) uses FUSE layer which is OSv does not implement and never will probably. For starters, we could limit the initial implementation to a read-only part.

**Comment by wkozaczuk** [comment]
Even though the commit bae4381d1d0558b7a684294e9203864f9652395c added initial VirtFS implementation, there still many outstanding elements missing or needing improvements:
- Implement `virtiofs_readdir()` 
- Implement `virtiofs_statfs()`
- Make implementation of `virtiofs_read()` more efficient it terms of exists by adding some kind of caching logic possibly like ROFS has
- Implement DAX Windows (see https://virtio-fs.gitlab.io/design.html)
- Allow booting OSv with VirtioFS mount as root (just like ZFS, ROFS or RAMS can now)

**Comment by foxeng** [comment]
Updating the list of pending items, feature-wise:
- `mmap` support. See https://github.com/cloudius-systems/osv/blob/5a2353cf7fd03212317f0b50178825ac10472bfb/fs/virtiofs/virtiofs_vnops.cc#L405
- `statfs`. See https://github.com/cloudius-systems/osv/blob/5a2353cf7fd03212317f0b50178825ac10472bfb/fs/virtiofs/virtiofs_vfsops.cc#L172

Gap-fillings, some improvements etc. are on the way. Unfortunately, due to current lack of time, this will be a somewhat long way (read: couple of months?).

**Comment by foxeng** [comment]
Totally agreed on replacing this with more fine-grained and easier to address issues.

Regarding mmap, the comment from the linux patch above is actually the description of how the DAX window works in the context of virtio-fs (and linux specifically, when referring to the guest page cache). Right now I am lacking the specifics around mmap in OSv (it's been a number of months since I looked into it and didn't end up implementing it back then), so I am not sure how this applies.

It might be of value, mainly for future reference, to leave a short overview of our current status here. Assuming a virtio-fs device supporting the DAX window:
- We try to satisfy all `read`s using the window. If for any reason that fails, we fall back to issuing a FUSE_READ to the host. See https://github.com/cloudius-systems/osv/blob/ef62b24d3b1dfe310aca7a1732abce223e4a124a/fs/virtiofs/virtiofs_vnops.cc#L258
- The first thing the DAX window manager (fs/virtiofs/virtiofs_dax.{hh,cc}) does is to check if the requested data are already in the window. If so ("cache hit"), it copies them back directly, satisfying the request. See https://github.com/cloudius-systems/osv/blob/ef62b24d3b1dfe310aca7a1732abce223e4a124a/fs/virtiofs/virtiofs_dax.cc#L34
- If the data are not found in the window ("cache miss") and the manager decides to bring them in, it issues a FUSE_SETUPMAPPING request, the data are mapped in the window and then copied back like above. See https://github.com/cloudius-systems/osv/blob/ef62b24d3b1dfe310aca7a1732abce223e4a124a/fs/virtiofs/virtiofs_dax.cc#L43

The ideal scenario for mmap IMHO would be to provide access directly to the DAX window, thus avoiding the (intra-OSv) copy that's part of `read`'s semantics.

**Comment by wkozaczuk** [comment]
@foxeng closing this one in lieu of two smaller specific issues I have just created - #1163 and #1164.
