### ISSUE TITLE
Shortcomings in the implementation of dlopen() and dlsym()

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1072]
@photoszzt discovered that our implementation of dlopen() and dlsym() is not complete. Here is the list of shortcomings:

- `dlopen` ignores all flags; the default behavior should be RTLD_LOCAL not RTLD_GLOBAL which is the current default 
- ~~`dlsym()`  does not implement RTLD_NEXT~~ - has been fixed by 42251396c7944bafc37fda391731614e6110c380
- ~~`dlsym()` does not lookup for symbols in the dependant objects for non-RTLD_DEFAULT and non-RTLD_NEXT handle (handle created with `dl_open`)~~ - this has been fixed by 3ffc18ac25075ca39f167fe2c7fe81cbd38c15ab

**Comment by nyh** [comment]
@photoszzt you have sent a two-patch series fixing `dlsym()` bugs - does this series fix all the problems listed here? If it does, please add the phrase "Fixes #1072" to the commit message, so that github will automatically close this issue once your patch is committed. If it only partially fixes these problems, please add the phrase "Refs #1072" to the commit message, and later explain here which problems remain open. Thanks!

**Comment by wkozaczuk** [comment]
Closing in favor of new issue #1108 that covers the only outstanding gap.
