### ISSUE TITLE
scripts: setup.py broken for Ubuntu versions < 19.10

### ISSUE THREAD

**Issue by rgo3** [cloudius-systems/osv#1085]
I tried using the setup script on Ubuntu 18.04 and it failed with this Error:
`E: Unable to locate package python3-dpkt`

I think commit 4a07fea6b15772a9a9b80dea86b0a0d01711727d broke the script for a couple of versions below 19.10 because the package `python3-dpkt` is not available there but only `pyhton-dpkt`.
I think a fix would be to separately install these two packages for the correct Ubuntu version and not `python3-dpkg` for all Ubuntu versions.

**Comment by nyh** [comment]
If you can test this on earlier Ubuntu versions, can you please fix setup.py? Should be fairly easy, as you noted: move "pyton3-dpkt" from the general list of "package" to the "packages" list of newer ubuntu versions.

However, a bigger question is whether everything will work afterwards. Recently @wkozaczuk made some changes to switch everything in OSv to Python 3 - because having Python-2-only scripts was becoming a risk because new distributions will soon drop Python 2.  If things don't work on Ubuntu 18.04 because of the Python 3 conversion, we will need to fix them (hopefully should be easy to fix what broke to support both Python 2 and 3?). But if (I hope it doesn't get to this...) this is too difficult, we will have to document that because of the Python 2 deprecation, we decided not to support Ubuntu 18.04 any more (and we should remove it from setup.py).

I don't think we should drop Ubuntu 18.04. It should *not* be necessary. Ubuntu 18.04 did have Python 3. If it didn't have "python3-dpkt", whatever this is, could we work around by having this script run on Python 2 if necessary (and use python2-dpkt) or fall back to not using this library at all?

**Comment by rgo3** [comment]
So what would I need to test to ensure my fix is not breaking anything? I changed `python3-dpkg` to `python-dpkg` locally (I have a machine with Ubuntu18.04) and was able to run the setup.py script then. But how can I be sure that this won't break any other script that were moved to `python3`?
In any case I am happy to make a PR for this.

**Comment by wkozaczuk** [comment]
Hi, you can you use docker files to pin to later/other Ubuntu version and
test setup.py this way.
