### ISSUE TITLE
arch_init_early_console crashes when kernel built with certain version of gcc

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1112]
This problem was initially discovered as we were working on [this issue](https://github.com/cloudius-systems/osv/issues/1106#issuecomment-726394167). I think it is actually more generic than just building AArch64 on Ubuntu. I think it stems from the fact that some versions of gcc(linker?) may generate kernel ELF in a way where global variables entries in GOT are 0 and need to be resolved by `elf::get_init()` and `arch_init_reloc_dyn()` before any functions using those can be called. So for example, `arch_init_early_console` which is called before `elf::get_init()` would not be able to properly use such global variables in this case and silently crash (hang) very early on. In x64 we are simply lucky that `arch_init_early_console` does not use any global variables as aarch64 version does.

There are at least 2 solutions to this problem:
1. Hide related symbols (which eventually should be hidden) and thus force the compiler not to use the GOT.
2. Call get_init(Elf64_Ehdr* header) before arch_init_early_console() which might be even easier but might cause some other unforeseen consequences.

Maybe there another compiler/linker flag that could help us in this matter that I am not aware of.

**Comment by nyh** [comment]
I can't say I remember why these variables need relocation or why this changed recently.
The first solution sounds good to me - I suggest that you test that it actually works. Maybe you can even make this global variable file-local ("static")?
About the call order, I'm ambivalent about what is the "right" order:
1. On one hand, get_init() should be called first, because it initializes stuff that C++ needs (global variables) to be initialized for everything to work.
2. On the other hand, init_early_console() should be called first, so that all other code, including get_init(), can print error messages (get_init() even has some error message in one case).
So I don't know which of the two are better. I think if we can get init_early_console() - and only that - to run before get_init(), it would be best.
