### ISSUE TITLE
Docker build fails 

### ISSUE THREAD

**Issue by Martin-Lndbl** [cloudius-systems/osv#1321]
After following the steps documeted in `./docker`, `./scripts/build image=native-example` fails with following error.

```bash
Building into build/release.x64
  GEN gen/include/osv/version.h
  GEN gen/include/osv/drivers_config.h
  GEN build/release.x64/gen/include/bits/alltypes.h
  AS arch/x64/boot.S
  CXX loader.cc
  HOST_CXX build/release.x64/gen-ctype-data
  GEN build/release.x64/gen/include/ctype-data.h
  CXX runtime.cc
runtime.cc:185:6: error: ambiguating new declaration of ‘void __cxxabiv1::__cxa_finalize(void*)’
  185 | void __cxa_finalize(void *dso)
      |      ^~~~~~~~~~~~~~
In file included from /usr/include/boost/core/demangle.hpp:32,
                 from /usr/include/boost/core/typeinfo.hpp:135,
                 from /usr/include/boost/detail/sp_typeinfo.hpp:20,
                 from /usr/include/boost/smart_ptr/detail/sp_counted_base_std_atomic.hpp:18,
                 from /usr/include/boost/smart_ptr/detail/sp_counted_base.hpp:48,
                 from /usr/include/boost/smart_ptr/detail/shared_count.hpp:29,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:28,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /usr/include/boost/format/alt_sstream.hpp:21,
                 from /usr/include/boost/format/internals.hpp:24,
                 from /usr/include/boost/format.hpp:38,
                 from include/osv/printf.hh:11,
                 from include/osv/debug.hh:17,
                 from include/osv/timer-set.hh:15,
                 from include/osv/sched.hh:28,
                 from runtime.cc:9:
/usr/include/c++/9/cxxabi.h:131:3: note: old declaration ‘int __cxxabiv1::__cxa_finalize(void*)’
  131 |   __cxa_finalize(void*);
      |   ^~~~~~~~~~~~~~
make: *** [Makefile:390: build/release.x64/runtime.o] Error 1
make failed. Exiting from build script
```

There is even a designated comment in `runtime.cc:68` and 3 lines of code that seem to be there to avoid exactly this error.
The gcc version `./scripts/setup.py` installed is `9.3.1`. My host system is NixOs.

**Comment by nyh** [comment]
In commit 4f67366db385450a36ca897bd3fe443015150703 from 2021 - that's three years ago - I noted that gcc 11 changed __cxa_finalize() from returning int, to returning void. I meant (as I explained in the commit message) to support both the new version and the pre-gcc-11 version. But I only checked it for gcc 10 and not the gcc 9 which you tried. I think you have two options now:

1. See what I did wrong in commit 4f67366db385450a36ca897bd3fe443015150703. I am guessing that some other header file included cxxabi.h and got the wrong __cxa_finalize. So please try to put the `#define __cxa_finalize __cxa_finalize_ignore` and `#undef __cxa_finalize` around **all** the header file includes instead of just the cxxabi.h include, and see if it helps.
2. Consider upgrading your choice of Linux. The example of 20.04 in docker/README.md was chosen in 2020, it's time to use a more recent distribution and not a 4-year-old distribution. If you get this working with some more recent Ubuntu (for example), please send a patch to docker/README.md to fix the example.

**Comment by Martin-Lndbl** [comment]
Thanks! It actually was the fedora-31 image that wasn't working for me.  Even though `ubuntu:20.04` also uses gcc 9.4 it doesn't run into the same issue, but into another one at linking time: ` /git-repos/osv/modules/lua/upstream/lua5.3/liblua53.so: undefined reference to dlopen`.
I took a look at `Dockerfile.builder`, which tries to access the osvkernels [docker registry](https://hub.docker.com/u/osvunikernel). This registry is outdated since it only contains `fedora-31` and `ubuntu-20.10` images.
Is this file still needed? Unless new docker images are added to the registry, it isn't very useful.  Only having [Dockerfile.builder-fedora-base](https://github.com/Martin-Lndbl/osv/blob/master/docker/Dockerfile.builder-fedora-base) and [Dockerfile.builder-ubuntu-base](https://github.com/Martin-Lndbl/osv/blob/master/docker/Dockerfile.builder-ubuntu-base) might be easier to maintain and more elegant since no changes to the docker registry from this side are necessary?

**Fedora**: I'll try to update the [Dockerfile.builder-fedora-base](https://github.com/Martin-Lndbl/osv/blob/master/docker/Dockerfile.builder-fedora-base) to `fedora-39` since that's the latest version the setup script supports.
**Ubuntu**: I'll try to update the [Dockerfile.builder-ubuntu-base](https://github.com/Martin-Lndbl/osv/blob/master/docker/Dockerfile.builder-ubuntu-base) to `ubuntu:22.04` since that's the latest version the setup script supports.
**For Nixos**: Would it be possible to build natively on NixOs if all dependencies specified in `scripts/setupy.py` are installed? Are there any other pitfalls I'm not aware of?
