### ISSUE TITLE
fix miscompile with ld.gold

### ISSUE THREAD

**Issue by avikivity** [cloudius-systems/osv#151]
ld.gold is a prerequisite for -flto, but currently osv doesn't boot if linked with it, and worse, the debug information is broken and causes gdb to abort.

**Comment by nyh** [comment]
According to https://sourceware.org/bugzilla/show_bug.cgi?id=18098 ld.gold's missing support for SORT_BY_INIT_PRIORITY was fixed in June 2016, a year ago, but according to the gold NEWS file this only reached release 1.14.

My Fedora 25's ld.gold is 1.11, so it doesn't have this feature yet.
Let's retest in another year :-)

**Comment by avikivity** [comment]
Fedora 26 has 1.12. Is there even a 1.14?

**Comment by nyh** [comment]
1.14 is the next release after 1.12: See their [NEWS file](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blob_plain;f=gold/NEWS;h=4ef3f78ba8ce5d620773d51ab43551be1bacc487;hb=HEAD).

**Comment by nyh** [comment]
According to https://www.phoronix.com/forums/forum/software/general-linux-open-source/1082277-gnu-s-gold-linker-is-stagnating-fedora-looking-to-punt-it-off-into-a-separate-package, gold has really stagnated and the GNU Binutils developers have instead gone back to improving the regular "ld", and added to it LTO support.
It will still be nice for OSv to be able to build with gold as the default linker, but commit d21e39f made even that irrelevant because we override the default linker anyway.
So it will be nice to retest, three years later, maybe gold actually works with OSv today and this issue can be closed - but if it doesn't, maybe we shouldn't invest any effort in fixing this and this issue can be abandoned (any maybe even closed as non-interesting).
