### ISSUE TITLE
Allow images without ZFS

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#195]
Some images, e.g., perhaps memcached and haproxy, are state-less and don't require a permanent filesystem like ZFS.
It would be nice to add the option to build an image using bootfs (like we had in the past) instead of ZFS. The expected benefits will be:
1. Faster boot, significantly less than 1 second (currently ZFS can add in some cases another 1 second to the boot time).
2. Lower memory use (though this probably has little practical significance in most non-toy images).

It's also possible to compile the kernel without ZFS support to make it smaller, again slightly improving on the same two points above..

**Comment by nyh** [comment]
James Root found another reason why an image without ZFS, with the entire application on bootfs, is useful:

It turns out that it's impossible to mount a ZFS filesystem on a read-only disk, because even if the mount is read-only, ZFS writes to some internal metadata anyway.
So if one wants to use a read-only image for OSv (e.g., to have multiple instances of qemu run from the same image file), ZFS will not work.

**Comment by jdroot** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by sassyn** [comment]
+1

On Mon, Feb 23, 2015 at 4:49 PM, James Root <notifications@github.com>
wrote:

>
> <https://camo.githubusercontent.com/a2840914d539225aaf8d395397d8dbc488a0740d/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f756e69636f64652f31663434642e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudius-systems/osv/issues/195#issuecomment-75553797>
> .
>



-- 
Regards,

Sassy Natan
972-(05)54-2203702

**Comment by nyh** [comment]
One inconvenient feature of our current ramfs implementation is that it (bootfs.o, containing the entire ram disk) needs to be linked, with ld, into the kernel's elf. Not so bad, but kind of ugly. It would have been nicer if the ramdisk dump (bootfs.bin), or a compressed version thereof, could just be concatenated to the end of the image, and the kernel would know to find it and open it into a ramdisk.

**Comment by jdroot** [comment]
How do you get additional files into bootfs? My thought would have been the bootfs.manifest, but from what I can see that is pushed to OSv after bootfs.o is compiled and after a zpool is created.

**Comment by pworner** [comment]
Neat.  No security breach can be persisted and live migration doesn't require shared storage or live block migration.

**Comment by jdroot** [comment]
So, I have been looking in to this with some success, [my changes are here](https://github.com/SEI-AMS/osv/tree/osv195). I modified build.mk to have a bootfs_only option, which (when set) builds bootfs.img instead of usr.img. It attempts to copy everything declared in usr.manifest in to bootfs.manifest to store it all in to the ramdisk. The changes are fairly small (and do not effect the build system when bootfs_only=false). The limitations are:

1. I believe there is a somewhat low file size limit on bootfs, when using my "Hello World" application I do not reach it, but building with image=cli fails.
2. My changes currently do not work without manually modifying usr.manifest.skel. Some of the entries (those with & and -> symbols) cause mkbootfs.py to fail. At the moment, I am just removing those entries, but I need to come up with a better solution.
3. fs/vfs/main.cc still attempts to mount /dev/vblk0.1 on /zfs. This is hard for me to think of a fix for, and would need some thought. The simple solution, would just be to check if /dev/vblk0.1 exists, and if so, mount it and then do the pivot from /zfs to /. However, this falls short in the situation where you want a static application that still has one data drive. My use case for this is something like MySQL. I could have MySQL configured to load its database from /data. While /data would be changing (as data is added), MySQL itself could be static. Ideally, to change out the database you would simply take your base MySQL OSv image, and attach the right disk to it. When doing this however, I believe it will show up as /dev/vblk0.1, which will cause OSv to attempt to mount it.

I am going to continue working on this because it is a use case I need to fulfill (and I really like OSv), if anyone has any comments/suggestions feel free to let me know.

**Comment by dorlaor** [comment]
On Fri, Feb 27, 2015 at 7:05 PM, James Root <notifications@github.com>
wrote:

> So, I have been looking in to this with some success, my changes are here
> <https://github.com/SEI-AMS/osv/tree/osv195>. I modified build.mk to have
> a bootfs_only option, which (when set) builds bootfs.img instead of
> usr.img. It attempts to copy everything declared in usr.manifest in to
> bootfs.manifest to store it all in to the ramdisk. The changes are fairly
> small (and do not effect the build system when bootfs_only=false). The
> limitations are:
>
>    1. I believe there is a somewhat low file size limit on bootfs, when
>    using my "Hello World" application I do not reach it, but building with
>    image=cli fails.
>    2. My changes currently do not work without manually modifying
>    usr.manifest.skel. Some of the entries (those with & and -> symbols) cause
>    mkbootfs.py to fail. At the moment, I am just removing those entries, but I
>    need to come up with a better solution.
>    3. fs/vfs/main.cc still attempts to mount /dev/vblk0.1 on /zfs. This
>    is hard for me to think of
>
>
Hi James,

Cheers for these changes, it will be nice to have this ram-only merged.
Can you create an additional ramfs and mount it as /dev/vblk0 ? This way the
logic remains the same. I don't think it's crucial so you're welcomed to
continue with
your approach too.

Thanks,
Dor

**Comment by jdroot** [comment]
I can look in to doing that this week. Do you happen to know how to increase the size of loader.elf? I believe the check size script is called with a max of 22MB. It mentions you can increase it by modifying some assembly files in arch/x64/, but I do not know enough about assembly to figure out how to modify that.

**Comment by dorlaor** [comment]
On Sun, Mar 1, 2015 at 6:41 PM, James Root <notifications@github.com> wrote:

> I can look in to doing that this week. Do you happen to know how to
> increase the size of
>

Don't get out of your way for it

> loader.elf? I believe the check size script is called with a max of 22MB.
> It mentions you can increase it by modifying some assembly files in
> arch/x64/, but I do not know enough about assembly to figure out how to
> modify that.
>
Nadav (CCed) probably knows.

**Comment by dorlaor** [comment]
On Sun, Mar 1, 2015 at 7:29 PM, Dor Laor <dor@cloudius-systems.com> wrote:

> On Sun, Mar 1, 2015 at 6:41 PM, James Root <notifications@github.com>
> wrote:
>
>> I can look in to doing that this week. Do you happen to know how to
>> increase the size of
>>
>
> Don't get out of your way for it
>
>> loader.elf? I believe the check size script is called with a max of 22MB.
>> It mentions you can increase it by modifying some assembly files in
>> arch/x64/, but I do not know enough about assembly to figure out how to
>> modify that.
>>
> Nadav (CCed) probably knows.
>
>

Yes, I do... ;-)

The reason for this annoying limit is our implementation of the compressed
kernel loading. I'll try to explain what's going on there:

For various reasons (image size, fasterkernel load, etc.) it is useful to
load a *compressed* kernel, instead of an uncompressed kernel. So we
compress the kernel (using the "fastlz" algorithm), and this is what is
loaded from disk during boot. The loader then decompresses the kernel and
runs the result.

Our decompressor is not set up "in-place" - you put the compressed kernel
in one area in memory, and it uncompresses the kernel into another area of
memory.

The target of the decompression is the address where our kernel is compiled
to live in, let's call this address X (it is 0x200000, kernel_base defined
in build.mk).
The source of the decompression is the address into which we have read the
compressed kernel. This can be basically *anything*. Let's call this
address Y. Because X is small, naturally Y > X.
This Y is defined in arch/x64/lzloader.ld and arch/x64/boot16.S (0x1800000).

Now, if the uncompressed kernel is larger than Y-X, while we uncompress it
from address Y to X, we can start overwriting the data we're decompressing,
which is likely to break. The script scripts/check-image-size.sh, called in
build.mk verifies the kernel isn't too big given the choice of Y.

You may think that the solution is trivial - just use a very large Y: if we
load the compressed kernel into address 1 gigabyte, and decompress it to
0x200000, there is no chance we'll overwrite the compressed data which is
far away at 1 gigabyte. This is true, but presents a new problem: Loading
the data into address of 1 gigabyte requires a VM with 1 gigabyte of RAM.
What if we want to run a VM with only 512 MB of RAM? Or even (in an extreme
case) 50 MB of RAM? Putting the compressed kernel at 1 gigabyte will ruin
this possibility.

The choice made by Eduardo Piva who wrote this code (and various people who
commented on his initial implementation) was to pick a fairly small Y,
0x1801000 (about 25 MB), which on one hand leaves allows us about Y-X = 23
MB of uncompressed kernel size which was deemed large enough, but on the
other hand does not impose a serious lower limit on the VM memory
requirement (25 MB + compressed kernel size is enough).

23 MB is quite enough for our normal kernel, but may not be enough if the
"kernel" includes a large ramdisk with a large application.

The first, easiest, thing you can do is to make this "23MB" a parameter.
While X (0x200000) is fairly fixed and you shouldn't change it, Y should
have been a build parameter. Instead it now appears in both
arch/x64/lzloader.ld and arch/x64/boot16.S, and the subtraction Y-X is
checked in build.mk (where calling check-image-size.sh). I think it will be
good to make Y a  build.mk parameter, just like X is (the parameter is
called "kernel_base" in build.mk, and it is passed to various places from
there).

A second, much nicer approach, and the one I prefer, would be to *decompress
in-place*: Put the compressed data so it will end at the end address of the
*uncompressed* kernel, and start decompressing (see discussion in
https://groups.google.com/forum/#!topic/comp.theory/4goPzMUWjos  for
example). With this technique, "Y" will be calculated automatically, and
will never impose additional memory requirement beside what the
uncompressed kernel actually needs.

A third, more complicated approach, would be to change how our ram-disk
works - instead of being part of the kernel and compressed with it, put it
*after* the kernel, and have the kernel read it after it has already booted.

Nadav.

**Comment by nyh** [comment]
On Sun, Mar 1, 2015 at 8:49 PM, Dor Laor <notifications@github.com> wrote:

> A second, much nicer approach, and the one I prefer, would be to
> *decompress
> in-place*: Put the compressed data so it will end at the end address of the
> *uncompressed* kernel, and start decompressing (see discussion in
> https://groups.google.com/forum/#!topic/comp.theory/4goPzMUWjos for
> example). With this technique, "Y" will be calculated automatically, and
> will never impose additional memory requirement beside what the
> uncompressed kernel actually needs.
>

Sadly, in-place decompression with fastlz is outlawed by a comment in
fastlz.h:

  The input buffer and the output buffer can not overlap.

I have no idea why this is so.

**Comment by jdroot** [comment]
That is very interesting, thank you for the explanation Nadav! It does seem like decompressing in place would be ideal as far as memory is concerned, however I wonder if that is worthwhile to spend time on. I think loading the whole kernel + application in to memory is a good idea but it does hit snags when the end goal (at least for this issue) is a read-only image. For example, it may not be worth it if you have a 200mb application to load the whole FS in to memory. I was looking through the FreeBSD revision that the ZFS driver was ported from, and noticed that there was a BSD licensed version of EXT2. Unlike ZFS, I believe EXT2 is capable of a true read-only mount. Given this, I think moving forward it might be easiest to make "Y" a build.mk parameter, which coupled with my modifications could allow you to build larger (however less efficient as the kernel + application grows) ram images and then as an alternate read-only mechanism allow a build.mk parameter which would use of a different file system that can be mounted on a read-only medium. I think it would lead to two separate make calls like the following:

make image=<something> bootfs_only=true kern_size=25MB # Builds a ramfs only image and "Y" is kern_size + 0x200000

make image=<something> usr_fs=ext2 # Which would be the same as the current build, except the root fs is ext2, which could then be run with something like: scripts/run.py --readonly

Thoughts?

**Comment by n03l** [comment]
What about compressing the kernel in multiple blocks? That would allow, I think, to decompress in place while making sure that the not yet compressed input is overwritten. 

It seems a small change, especially if compared to adding support for ext2.

**Comment by nyh** [comment]
Since commit 714cfd97e48ba5fecba224430762d2c8aac7c0eb we now have an option to build images which puts all the files in the ramdisk included with the kernel. This solution is not as useful for big packages as the solution proposed in #646, but can be useful for small images. To build images where everything is put on the ramdisk, instead of zfs, pass the "fs=ramfs" to scripts/build. See the above commit for a more elaborate description of this feature.

As an example, with fs=ramfs, scripts/build image=rogue reduces the image size from 12 MB to 7 MB, reduces the mimimum needed memory from 56 MB to 40 MB, and reduces boot time from 0.9 seconds to 0.8

Note that currently, even with fs=ramfs, the ZFS code is always included inside the kernel, and a failed attempt is always made to mount /dev/vblk0.1 on /zfs. However, ZFS does not come into play after the boot (e.g., no ZFS threads exist during the run).
