### ISSUE TITLE
Mono support?

### ISSUE THREAD

**Issue by dealproc** [cloudius-systems/osv#34]
Is there any user stories dedicated to utilizing Mono on this platform?  This stuff sounds interesting... but not being a Java developer, it may be lost on me.

**Comment by tijoytom** [comment]
I have simple C# AOT Hello work example running on OSV

Here's where I will put the instructions if anyone want to try it 
https://github.com/tijoytom/capstan-example

To give some background 

CoreRT (https://github.com/dotnet/corert) is the new C#  AOT compilation technology , where you  compile your C# code down to native machine code and produce a single binary with the runtime and the libraries. 

CoreRT support carious backend compilers since it have the ability to produce C++ code  , which can then be compiled using clang , gcc etc.. Also there  is the native code generation using the full .NET code generator ( RyuJIT) which is the default . 

The workflow looks like this 
Write your C# code  -> Compile it to C++ using CoreRT compiler -> use clang to compile it to shared library.

**Comment by geraldo-netto** [comment]
Dear Friends,

@wkozaczuk has provided mono support
We still need to work out some syscalls
But you can check a sample C# app here:
https://github.com/cloudius-systems/osv-apps/tree/master/mono-example

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
Closed by https://github.com/cloudius-systems/osv/commit/d39860d112c33959970405006469604ad543a415
