### ISSUE TITLE
got "exception nested too deeply" when I typed Ctrl-C after exit command

### ISSUE THREAD

**Issue by syuu1228** [cloudius-systems/osv#374]
I got "exception nested too deeply" when I typed Ctrl-C just after executed "exit" command on crash shell.

```
$ ./scripts/run.py
OSv v0.10-238-ge719f71
eth0: 192.168.122.15
 
[/]% exit
Have a good day!



exception nested too deeply
[backtrace]
```

**Comment by nyh** [comment]
I believe this problem is identical to issue #580 - basically, what we have here is exit() unmounting the filesystem, and if after that unmount and before the final poweroff some application code happens to run, this will get a page fault which will crash (the crash will often look like a "nested exception" because the page fault handler itself will crash when it needs the file backing the object).
