### ISSUE TITLE
Internal Lua CLI accessible over SSH

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#437]
When running internal Lua CLI, it is desirable to have it available over SSH, similar to CRaSH CLI.

On the cloud, SSH key should be download from meta data.
CRaSH CLI already have this functionality
https://github.com/cloudius-systems/osv/issues/132

**Comment by phillaverdiere** [comment]
Is this issue still a problem?

**Comment by wkozaczuk** [comment]
It would be best to get the answer from the original author - @tzach :-) But I am thinking it might be not relevant or simply implemented long time ago bit never closed. According to this - https://github.com/cloudius-systems/osv/wiki/Command-Line-Interface-(CLI)#connecting-to-osv-using-host-cli-over-https - one case use cli with https (which is built on SSL just like ssh). Shall we close it?

**Comment by tzach** [comment]
@wkozaczuk you are welcome to close. My brain only have TTL of 2-3 years of issues.

**Comment by lightpriest** [comment]
Back when the Lua cli was written, it had two purposes. One was to provide an interactive shell from inside a running VM. The other was to be used outside as a way to interact with a running VM using its API.

I haven't followed the project for a while, so a little refresher due. That said, the initial shell implementation was based on CRaSH (a JVM based shell) which provided a shell (with SSH, etc.) to a generic JVM process. We used this in the first few setups of osv that also ran a JVM. The Lua CLI was the more generic implementation that would work either with JVM or not.

There was no SSH implementation with Lua because the standard ssh daemon forks when a client connects, which was not possible in osv. If it's not the case anymore, then it might be possible to have sshd running. In any case, the thinking was that the VMs were to be accessed via an HTTP.

**Comment by nyh** [comment]
This still a valid feature request - but only if someone actually **requests** this feature... As nobody seems to request it - nobody expressed any interest in this feature for years - I'm closing this feature request, but feel free to reopen it if anyone does request it.

As @wkozaczuk said, we now have alternative methods to do the same thing (i.e., someone can run the lua shell on your own machine, and it contacts the OSv host via REST over HTTPS) so ssh isn't strictly necessary any more - even if some people would have still found it more convenient than installing an osv-specific shell on the orchastration machine.
