### ISSUE TITLE
dlopen() and program::add_object() needs reference counting

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#47]
According to Linux's dlopen(3) manual page, "If the same library is loaded again with dlopen(), the same file handle is returned.  The dl library maintains reference counts  for  library handles,  so a dynamic library is not deallocated until dlclose() has been called on it as many times as dlopen() has succeeded on it."

Our dlopen() uses our program::add_object(), and neither have this necessary reference counting on the handles they return.

I am writing now a convenience function osv::run() to run a shared-object's main (similar to elf-loader.cc), and this reference counting is important because without it, we cannot run the same object more than once concurrent with itself - without the reference count, the first run to finish will unload the object, and the still-running instances will crash.

NOTE: This reference count is completely unrelated to the issue of concurrent use of dlopen()/dlclose()/dl_iterate_phdr(), which is also something we need to fix (I have a patch for that, but it's too long to fit in the margin).

**Comment by daohu527** [comment]
How do you deal with the problem of implicit dependence? Reference count for `implicit dependence` is different achieve

**Comment by wkozaczuk** [comment]
@daohu527 What do you mean by "implicit dependence"? Can you please give an example and elaborate a bit? Also, I wonder given this issue is closed, shall we discuss all this on the mailing list and simply reference this issue?

**Comment by nyh** [comment]
> How do you deal with the problem of implicit dependence? Reference count for `implicit dependence` is different achieve

I'm not sure I understood your question (if I didn't, let's continue this on the mailing list please, not on an issue closed 7 years ago!), but you should know that a loaded object's reference count can be increased by many things - not just because it was dlopened()ed many times. It is also increased, for example, when a different object called a function which was resolved to this dlopened file. The loaded object will only really be unloaded once all those references are deleted.

The relevant code is in core/elf.cc. For example, in `object::resolve_pltgot()` which is called to resolve a symbol (a function) which has lazy binding, we have:
```c++
    if (sm.obj != this) {
        WITH_LOCK(_used_by_resolve_plt_got_mutex) {
            _used_by_resolve_plt_got.insert(sm.obj->shared_from_this());
        }
    }
```
In this code, `sm.obj` is a *different* shared object from which we resolved a function in this shared object. So we add to the list `_used_by_resolve_plt_got` in this object a reference to that other object. So that other object's reference count increases. That other object cannot be unloaded until this object is unloaded first, and the other object's reference is removed from its `_used_by_resolve_plt_got` list.

**Comment by daohu527** [comment]
## implicit dependence
Thank you for your patient answers, I didn’t notice that this is a question 7 years ago. My question is mainly focused on `dlopen`. For example
```
A
B -> A
```
1. We first load A, then dlopen with A reference count is 1
2. We dlopen B, it will recursive dlopen A, because the dependency(`implicit dependence`). We don't load A again but just returen the handle in memory, and A reference count is 2.
3. We unload A, then A is still in memory, and reference count is 1.
4. We unload B, then A is remove from memory now, because the reference count is 0.

## problem
The implicit dependence here refers to **implicitly loading A when loading B**. If we have implemented a reference count about A, we will not know the dependence, and when we load B, we will not add the count, then after unload A, the A is already in memory, but we said A is not.

In many cases, there is no problem, but if you need to perform some initialization operations when loading so, you will wonder why initialization is not done when loading.

So my question is, if you implement the reference counting of the so library yourself, then how to find the dependencies will be a serious problem.

If you think it is necessary, I am very happy to discuss this in mail list. daohu527@gmail.com

**Comment by nyh** [comment]
The reference counting you describe in the first part of the above comment is correct (the second increment of B's reference count happens in `object::load_needed()` where it saves a reference to B's in "`_needed`").

But I don't understand the "implicit" dependence you mention... It seems you mean that for some reason your application wants to know when or whether B is loaded, and the application is surprised when it automatically gets loaded when A was loaded. The question is how do you want OSv to help you know when B gets loaded and unloaded? Why isn't it enough that OSv loads and unloads B as needed? Also note that if B has **constructors**/**destructors** (functions that run on load/unload), they also run automatically. Let's continue discussing this on the mailing list - osv-dev@googlegroups.com.
