### ISSUE TITLE
Behavior of Ctrl+C is not intuitive when OSv is run with interactive shell

### ISSUE THREAD

**Issue by tgrabiec** [cloudius-systems/osv#49]
Currently when you hit Ctrl+C the qemu terminates and the OS is brought down. If I start OSv with intent to use its command line interface this behavior is not intuitive as I expect that when I'm in a shell hitting ^C will clear the command line.

A solution to this could be to:
- start qemu with -nographic (unless in "daemon" mode), key strokes like Ctrl+C will be passed to the guest
- change the CLI to react on Ctrl+C by clearing the command line
- add a command to shut down the OS (convenience)

Downside of this approach would be that one would not be able to kill OSv from console using Ctrl+C. 

I'm interested in your opinions on that one.

**Comment by mikelo** [comment]
what right-control-C passes to OS and left-control-C to the guest?

**Comment by nyh** [comment]
Hi Michele, giving right-control-C and left-control-C different behavior is not something that Unix users would expect. Worse, when the guest is using the serial port instead of VGA (this is what happens by default when you run through qemu), there is no support at all for left or right control keys (pressing control-C, of either variant, will send character \003 on the emulated serial port). So your idea cannot work.

In any case, I think the current behavior is quite reasonable, don't you? Right now, control-C is passed to the guest, which might do anything it pleases with it, but the default behavior is to power off the guest. If the guest catches control-C and you nevertheless want to kill it, qemu provides a convenient way to kill a guest type "control-A x" (that's "control-A" followed by "x"). That can be used for killing any guest in qemu, not just an OSv guest.

So I think the current behavior is most reasonable, and most similar to what users would expect from Linux guests, so I think we should keep this issue closed.
