### ISSUE TITLE
build: failure because of old file modules/tests/usr.manifest

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#498]
I just got "make image=tests" failing because modules/tests/usr.manifest listed incorrect files.

This usr.manifest is built automatically during build from usr.manifest.skel. However, it seems recently usr.manifest.skel was updated (to use a newer version of boost) and yet "make" did not rebuild usr.manifest.

I tried "make clean" and hoped to get a clean build, but it didn't help - "make clean" did not remove usr.manifest. This is a bad - "make clean"'s module cleanup stage should remove this file too.

Manually removing modules/tests/usr.manifest solved my build problem.

**Comment by wkozaczuk** [comment]
@nyh can you confirm if this issue still happens? The tests makefile has changed quite dramatically since this issue was raised 7 years ago. 

Currently, the tests makefile generates `usr.manifest` every time you build the test image so any old manifest with bad files would simply be refreshed. Also, the makefile has `clean` target that should remove all manifest files.

Am I misunderstanding the issue?

**Comment by nyh** [comment]
It seems like maybe in the past, usr.manifest wasn't in the build/ directory? I'm not even sure. Closing.
