### ISSUE TITLE
missing pthread_setaffinity_np()

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#520]
We have a do-nothing (and failing) stub for pthread_setaffinity_np().

We've had in the past at least two patch sets sent to the mailing list which unsuccessfully trying to do this. But although these patches were incomplete, there might be things to learn from them. We can also start with the easier case of a thread controlling it's own affinity (thread==pthread_self()).

https://groups.google.com/forum/#!searchin/osv-dev/sched$20set_cpu/osv-dev/uFgHpxhCF6E/tYuVP1rTjW8J
https://groups.google.com/forum/#!searchin/osv-dev/pin$20thread/osv-dev/wZD_-TQWoW8/tgveSsZnGRgJ

**Comment by justinc1** [comment]
About usage of pthread_setaffinity_np in Open MPI.

The simplest Open MPI app doesn't start threads on its own, and for those I can add code at start of each thread routine. The problem is, at that time I don't know to which cpu thread should be pinned (we start communication thread, and info about required pinning comes later over TCP communication channel - e.g. the communication thread must be running at that time).

More complex Open MPI apps start additional threads, often even before their Open MPI part gets initialized. For that case, all old threads are first pinned. The one created later are probably pinned as whole process is pinned (I guess its so). The 'pin all old threads' seems to be very 'intentional' - code loops over all thread a few times to recheck/re-pin them, to check if new threads as created just at the current moment etc; I guess they had quite some problems with some threads randomly slipping unnoticed from pinning part.

Hope this justifies required effort.

**Comment by nyh** [comment]
Updating on the original issue report, by now we already support pthread_setaffinity_np for the special case of pinning *this* thread to one CPU - see commit 0238e118f967b94d3c6f5322a4548d7f2d6aa937.

Justin is right that one thread pinning a different thread is not yet supported.

Justin, please also note that as far as I remember, pinning is not currently inherited: If a pinned thread creates a new thread, the new thread is not pinned. If this is contrary to what happens in Linux, can you please open a separate bug on that?

**Comment by justinc1** [comment]
Thanks for note, added #761

**Comment by nyh** [comment]
Here is an idea on how a function to pin a different thread to some CPU might be implemented.
This is not necessarily the best or most efficient way to do this, I wonder if there's an easier way to do this. But I think something like the following would work and would be "good enough":

1. Start helper thread pinned to the current cpu of the target thread

2. Helper thread disables irq and verifies that the target thread is on this cpu. If not, it re-enables irq, pin()s itself to target's cpu and goto 2

3. Helper thread now knows the target thread belongs to CPU but is not running, so it can send the target thread to a different cpu, similar to the way that thread::pin() and cpu::load_balance() do this. We probably need to consider the state of the thread being migrated:
   a. If the thread is in "waiting" state, the code can be similar to that of pin() without the extra "wakeme" thread (we can modify the thread's variables and then use normal wake() on it, since we're already running from a different thread - like the "wakeme" in the pin() thread).
   b. If the thread is runnable ("queued" state), the code to migrate it is similar to that cpu::load_balance() (we need to remember to remove it from the run queue, and change its state) - just remember to keep the thread pinned.
    c. If the thread is in any other state, I'm not sure what to do. Maybe it's safest to just verify in step 2 that we're not in any other transient state (and fail if in states like terminating, etc.)

4. At this point the helper thread exits. The pin-of-different-thread function waits for the helper thread it created to exit (i.e., joins it). This is useful so when this function returns, the caller knows the pinning has already taken place.

There is another complication we'll have to consider: What happens if at step 2, we discover the thread is already pinned to some CPU? This might be fine (we are simply changing previous pinning), but can also be a problem if the user was in the middle of a transient migration_lock - in that case it would be wrong to migrate it and the loop of step 2 should probably try again several times in a usleep() loop (assuming that migration_lock is held for very short durations). We may need to add a separate thread field to mark an intentionally "pinned" thread (perhaps even give a list of allowed cpus, not just one, as in pthread_setaffinity_np) separately from the _migration_lock counter, so we can tell apart the two cases.
