### ISSUE TITLE
imgedit.py can't always connect to qemu-nbd

### ISSUE THREAD

**Issue by jpeach** [cloudius-systems/osv#534]
There are a couple of issues with imgedit.py being able to reliably connect to qemu-nbd.

First, it connects to "localhost". On my Fedora20 VM, "localhost" was configured to resolve to ::1, and emu-nbd seems to only listen on IPv4 addresses. I fixed this by editing imgedit.py to connect to "127.0.0.1".

Second, imgedit.py assumes the port number that qemu-nbd is going to listen to. It should be choosing an explicit port and passing that as the argument to the qemu-nbd --port option and to the nbd_client port= argument.

**Comment by wkozaczuk** [comment]
We could do something similar to https://github.com/cloudius-systems/osv/blob/b3aef656ddd79df7299c385d7ad9e28e813727ea/scripts/upload_manifest.py#L16-L20 to fix it.

**Comment by nyh** [comment]
Two years after this issue was opened, imgedit.py was changed in commit 464f4e05c70e756a1a54e3751c710393371b7f5f to open a random port in the same way described here. 

The fact we allow qemu-nbd to default to listening to any IPv4 address but then connect to localhost, remains. The real solution is very simple and described in issue #709: imgedit.py should call qemu-nbd with "-b 127.0.0.1" and connect to 127.0.0.1, instead of localhost.
So I'm closing this issue in favor of #709.
