### ISSUE TITLE
Preparing HVM images

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#581]
Hi folks,

I'm mucking my way through EC2 deployment (based on an old Mirage deployment), however, OSv currently doesn't support PV, only HVM. The wiki docs say that I can use a windows instance to bootstrap, but there doesn't seem to be an example. I'm currently looking at the internal scripts/release-ec2.sh, but I was just wondering if it's reasonable to use capstan as the basis instead of build/release.x64/user.img:

1) generate full image using capstan build
2) qemu-img convert -f blah.qemu -O blah.img
3) ec2 magic
4) run new instance

Is it also possible to use s3 for storage rather than having an ebs?

Any hints would be most appreciated!

Cheers,

Rowland

**Comment by glommer** [comment]
On Wed, Feb 4, 2015 at 10:43 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi folks,
>
> I'm mucking my way through EC2 deployment (based on an old Mirage
> deployment), however, OSv currently doesn't support PV, only HVM. The wiki
> docs say that I can use a windows instance to bootstrap, but there doesn't
> seem to be an example. I'm currently looking at the internal
> scripts/release-ec2.sh, but I was just wondering if it's reasonable to use
> capstan as the basis instead of build/release.x64/user.img:
>
> 1) generate full image using capstan build
> 2) qemu-img convert -f blah.qemu -O blah.img
> 3) ec2 magic
> 4) run new instance
>
> Is it also possible to use s3 for storage rather than having an ebs?
>

It is possible to use S3 storage, but it is very, very slow. This is the
reason why we have moved away from it - so beware!

As far as I understand, the release-ec2 script does use S3 storage, and it
is the exact description of the process we used to convert windows images
into OSv images.

Look, for instance, around line 270:

    echo_progress Creating bucket $OSV_BUCKET
    aws s3api create-bucket --bucket $OSV_BUCKET
           ^^^^^

I haven't used it in a while because scripts/ec2-make-ami.py is so, so much
more efficient (but it does require you to be running it inside another
amazon linux VM)

As for capstan, as soon as it finishes its build, it will make all images
available in .capstan, and from there you should be able to convert them.

From the release script side, take a look at the --override-image option.
It should allow you to specify the image created in the previous step.

(release-ec2 --help for a full list)

**Comment by rowlandwatkins** [comment]
Awesome, I spun up an instance and scripts/ec2-make-ami.py works a treat :)

Now, is there a switch when building OSv images to set the virtual size? 11GB is a bit much for my needs and I don't want to do damage to the image after my app has been installed...

Cheers,

Rowland

**Comment by tzach** [comment]
If you are building OSv from source you can use the [fs_size_mb](https://github.com/cloudius-systems/osv/blob/master/build.mk#L55)
I do not think Capstan have a similar option.
@penberg is it so?

**Comment by rowlandwatkins** [comment]
@tzach Works a treat, thanks!

I'm assuming capstan can't do anything like that, without messing around with the underlying image template.

**Comment by rowlandwatkins** [comment]
Closing, thanks for all the help, running on EC2 works great!
