### ISSUE TITLE
error while ./script/build

### ISSUE THREAD

**Issue by nirmoy** [cloudius-systems/osv#611]
/osv# ./scripts/build
Building into build/release.x64
  GEN gen/include/osv/version.h
realpath: unrecognized option '--relative-base=.'
Usage:
 realpath [-s|--strip] [-z|--zero] filename ...
 realpath -h|--help
 realpath -v|--version
expr: syntax error
./scripts/build failed: arch=`expr $OUT : '.*\.\(.*\)'`

uname -a
Linux nirmoy-Inspiron-3542 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nyh** [comment]
On Fri, Apr 3, 2015 at 8:02 AM, nirmoy <notifications@github.com> wrote:

> /osv# ./scripts/build
> Building into build/release.x64
> GEN gen/include/osv/version.h
> realpath: unrecognized option '--relative-base=.'
>
I don't understand this - according to
http://git.savannah.gnu.org/cgit/coreutils.git/commit/?id=77ea441f79aa115f79b47d9c1fc9c0004c5c7111,
it seems realpath was added to GNU coreutils already with this
"--relative-base" thing, so how can a recent Ubuntu have one without it?

What package and version does your "realpath" come from?

Anyway, I can easily change this code to use "readlink" instead of
"realpath" if I can't rely on a consistent version of realpath.

**Comment by nirmoy** [comment]
realpath version 1.19
package I guess its "trusty" as per /etc/apt/sources.list.

**Comment by nyh** [comment]
It turns out that a "realpath" utility first appeared in FreeBSD 4.3 (in 2001), Debian added a similar utility in 2002, and only in 2011, GNU coreutils added this utility, with, as usual, a gazillion new options.

Ubuntu is still using Debian's version of this utility, *not* GNU's, while the one I tested on Fedora uses GNU's new version.

I'll prepare a patch to use readlink(1) instead.
