### ISSUE TITLE
scripts/build doesn't build java components after clean

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#622]
Hi folks,

When building from clean with the following:

[[[
scripts/build modules=httpserver,cloud-init,mgmt,ruby fs_size_mb=1024
]]]

java/cloudius, java/jolokia-agent, java/runjava are not built. This causes the build to fail when copying artifacts during the openjdk8 build, which then fails the build script.

This also happens when explicitly including the jdk module.

Cheers,

Rowland

**Comment by nyh** [comment]
I can't test the above command line because 1. "mgmt" no longer works (unless you have a good reason to resurrect it, I recommend "cli" instead) and 2. "ruby" doesn't work on my system.

But I can reproduce the same problem with:

```
$ scripts/build clean
$ scripts/build image=openjdk8-fedora
...
Exception: Path does not exist: /home/nyh/osv/java/jolokia-agent/target/jolokia-agent.jar
```

Trying `scriptsw/build image=java` does work, so apparently some missing prerequisites - I'll take a look.

**Comment by nyh** [comment]
Fixed by osv-apps.git commit 3e8032e3985e309f3b26a9ca88694a30dbfdb76c. Can you please verify your problem is fixed (do "cd apps; git checkout master; git pull") and then close this issue? Thanks.

**Comment by rowlandwatkins** [comment]
@nyh Many thanks, build now works after clean!
