### ISSUE TITLE
Upload file with executable bit set.

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#681]
I some existing code, I currently replaced some access(path, X_OK) with F_OK, just because I can't figure out how to set the executable bit. I see that /cli/cli.so has executable bit set, so it should be possible. I tried that:
```
curl -X PUT http://192.168.122.210:8000/file/%2Faa?op=WRITE&permission=755&content=asdfasdf
curl 'http://192.168.122.210:8000/file/%2F?op=LISTSTATUS' | python -m json.tool | grep -C5 aa
```
But /aa has 644 mode. POST even doesn't have permission param. What could be next to try?

**Comment by benoit-canet** [comment]
I will discuss this issue with Nadav tomorow to decide what is best to do.

Best regards

Benoît

**Comment by nyh** [comment]
In modules/httpserver/api/file.cc, the code for handling this "op=WRITE" thing is:
```c++
        case ns_putFile::op::WRITE:
        {
            auto flags = ios::out;
            flags |= (req.get_query_param("overwrite") == "true")? ios::trunc : ios::app;
            ofstream f;
            f.exceptions ( std::ifstream::failbit | std::ifstream::badbit );
            f.open(full_path,flags);
            f << req.get_query_param("content");
            f.close();
        }
```

Indeed, the "permission" variable (set a few lines above) is ignored here, and plays no part in the creation mode of the new file. So this is indeed a bug, and should be fixed.

By the way, C++'s ofstream.open(), unlike the Unix open()'s third parameter, has no way of specifying the new file's creation mode. This is perhaps because C++ tries not to be Unix-specific, and file permissions isn't a standard thing.

I can think of two solutions: 1. use mknod() to create the file with the required permissions before opening it, or 2. use chmod() to change the file's permissions after opening it.

Finally, I'd like to note that if you upload files into an image using one of our image-building tools (scripts/build or Capstan), the file permissions will be copied ok. This bug only effects the REST API.
