### ISSUE TITLE
How to modify cassandra.yaml cofiguration in prebuilt qcow2 Cassandra Virtual Appliance

### ISSUE THREAD

**Issue by pushpendrachaturvedi** [cloudius-systems/osv#685]
I am trying to make a 4-node Cassandra cluster with OSv's Cassandra Virtual appliance qcow2 images available at http://osv.io/downloads/.
I installed one image on my local KVM.

But i am unable to reach cassandra.yaml fiie.
I want to edit that file to edit configuration settings like cluster name, seeds etc to make a cluster
How can i reach that file?

All i see is 

Listening for cql clients....
Listening for thrift clients.....

Please help

![img_20151125_104945458](https://cloud.githubusercontent.com/assets/9261033/11393895/afe6857a-9362-11e5-9685-85632bf800e4.jpg)

**Comment by nyh** [comment]
@tzach, If this issue is a bug at all, then I would consider it a website bug - the website invites you to download an existing "Cassandra image" but doesn't explain how to use it, including how to change the configuration.

If you build the image yourself (with scripts/build or Capstan), you have the opportunity to upload a different configuration file to the image.

Finally, you *can* upload files into the image if the image includes an http server, and this is perhaps what the manual page should explain. However, I hope this http server is not open without a password, or it's a huge security risk, but I don't know any details how this password is set (@tzach might know).

It might also be possible to grab the configuration file from some sort of "cloud init" mechanism, but again, I don't know anything about it (@tzach might know).

Let's try to focus this bug, or close it and move this discussion to the mailing list.

**Comment by tgrabiec** [comment]
2015-11-25 13:13 GMT+01:00 nyh <notifications@github.com>:

> @tzach <https://github.com/tzach>, If this issue is a bug at all, then I
> would consider it a website bug - the website invites you to download an
> existing "Cassandra image" but doesn't explain how to use it, including how
> to change the configuration.
>
> If you build the image yourself (with scripts/build or Capstan), you have
> the opportunity to upload a different configuration file to the image.
>
> Finally, you *can* upload files into the image if the image includes an
> http server, and this is perhaps what the manual page should explain.
> However, I hope this http server is not open without a password, or it's a
> huge security risk, but I don't know any details how this password is set (
> @tzach <https://github.com/tzach> might know).
>
> It might also be possible to grab the configuration file from some sort of
> "cloud init" mechanism, but again, I don't know anything about it (@tzach
> <https://github.com/tzach> might know).
>

Securing RESTful API is described here:

https://github.com/cloudius-systems/osv/wiki/Configuring-SSL

Uploading files using cloud init is described here:

https://github.com/cloudius-systems/osv/wiki/Cloud-init

**Comment by pushpendrachaturvedi** [comment]
How can i reach linux type command line/terminal to execute certain commands in this virtual appliance image, is there any way?
As i pasted in the picture, as soon as i start the virtual appliance, cassandra service is started itself with default configuration and i have no idea how to stop or restart it? 
Does or does OSv not offer such command line functionalities?

Will i get command line interface (similar to ubuntu terminal) if i built the image with scripts/build or Capstan?

If i use Ctrl+C to enter next command , the VM stops, is it that will always happen with OSv?

For example, I am building a 4-node Cassandra cluster. i need to dynamically assign listen_ip and seed or cluster name in a cassandra.yaml configuration file of each node with different values. How can i do that?

Can i only make these changes while building the image?
 Can i not modify values in cassandra.yaml file after the image is built?

Thanks.

**Comment by nyh** [comment]
I'm closing this issue because it is more of a discussion than a specific issue that can be fixed. Please reopen a more specific issue when it's clearer what the actual problem is. Feel free to continue discussing this on the osv-dev mailing list.

But I'll also take the oportunity to answer some of your questions - if you have more questions, please do use the mailing list, and not this bug tracker:

OSv is intended to be a single-process operating system, where you run a single application on a VM, and that's it - you would not normally have a shell and ssh etc. running in parallel to your main application. Doing this is possible (we do have a shell that can run in a thread in parallel to your main application) but not recommended, and I don't believe our packaged Cassandra image includes a shell.

As I explained earlier, there are four better ways in OSv to get your correct configuration file into the image than putting a shell and an editor into an image:

1. Build the image (with scripts/build or Capstan) already with the desired configuration file. Clearly you cannot do this for an image you didn't build yourself.
2. Put a tiny http server in the image (we have it in the build you used) and use it to *upload* your configuration file. Tomek sent you a link on how to set this up securely (you don't want to open up your image to anybody off the Internet to upload files into your image).
3. Use "cloud-init" (I believe it is also included in the image you use?) or similar feature to have the image fetch its configuration file from a known location every time it boots up.
4. Use "Capstan" to build an image derived from the one you use, with one new uploaded file.

Option #4 is perhaps the easiest if you already know how to use Capstan. I would personally have loved to see this capability outside of Capstan, as a separate script (it's easy, to upload new files into the image you just run its cpiod.so - just as we do in scripts/build - and upload the files you want).
