### ISSUE TITLE
Missing __realpath_chk which breaks any new builds using the java.nio libraries with openjdk8-fedora

### ISSUE THREAD

**Issue by joelthompson** [cloudius-systems/osv#701]
This seems similar to #657, and it's breaking any new builds that use the java.nio libraries with the openjdk8-fedora app. The openjdk8-fedora app is configured to pull down the latest JRE from Fedora Rawhide upon every build, and sometime last week they published a new binary that appears to turn on FORTIFY_SOURCE.

As an repo, look at https://gist.github.com/joelthompson/7f7a716bf3b16599c051#file-repro-sh which is run against the latest bento/fedora-22 vagrant box, clones against master of the osv GitHub repo, and includes a pretty minimal HelloWorld testcase. Running it the first time, using the default openjdk8-fedora, produces a crash. Downgrading to the JRE from FC22, as shown, will produce the desired results and not a crash.

Thanks @copumpkin for the help in tracking this down!

Of course, there could be additional _chk functions which are missing and are breaking openjdk8-fedora, but I haven't had time to try to track this down any further.

**Comment by nyh** [comment]
Thanks, good analysis.
The specification of the __realpath_chk ABI can be found in http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/libc---realpath-chk-1.html
If you can send a patch to the mailing list (should be quite simple), I will be happy to commit it.

By the way, http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/libcman.html lists *all* the *_chk functions (and other functions) of glibc, so someone could use it to find all the functions missing in OSv instead of finding them one by one.

**Comment by nyh** [comment]
A more updated LSB ("Linux Standard Base") document:
http://refspecs.linux-foundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/libc.html

**Comment by joelthompson** [comment]
I've got my trivial HelloWorld repro working now, though I'm not sure I've done the right things.

I added __realpath_chk in libc/misc/realpath.c (seems like a reasonable place to put it, though glibc has it in debug/realpath_chk.c).

Now, the relocater complained about missing fpathconf, which appears to be in musl/src/conf/fpathconf.c, so I added musl += conf/fpathconf.o to to the Makefile.

Then, the relocater complained about missing inotify_rm_watch. I noticed that it's in musl/src/linux/inotify.c, but there are also stubs in libc/inotify.cc. I don't know why that wasn't showing up for the relocator, readelf -Ws build/release/libc/inotify.o showed _Z16inotify_rm_watchii, but when I just added musl += linux/inotify.o to the Makefile, that complained about conflicts, so I had to comment out libc += inotify.o. At this point, it compiled and ran without crashing. This is the part I don't understand -- I would expect the stub inotify_rm_watch to still be visible to the relinker.

Anyway, is this the right approach? Pull functions from musl in as needed? And, if so, why the inotify stubs instead of just pulling in musl's inotify implementation? Sorry if these are n00b questions, I had barely even heard of OSv a week ago! Let me know, and I'll try to get a patch prepared and sent out.

**Comment by nyh** [comment]
Hi, some of these things are not really related to this specific
bug-tracker issue, so we should probably move their discussion to the
mailing list.

On Fri, Dec 25, 2015 at 1:37 AM, Joel Thompson <notifications@github.com>
wrote:

> I've got my trivial HelloWorld repro working now, though I'm not sure I've
> done the right things.
>
> I added __realpath_chk in libc/misc/realpath.c (seems like a reasonable
> place to put it, though glibc has it in debug/realpath_chk.c).
>

Yes, looks good to me. If you can send a patch to the mailing list, I'll
review it. Please include a "Signed-off-by" line in the patch as explained
in the "CONTRIBUTING" file.

> Now, the relocater complained about missing fpathconf, which appears to be
> in musl/src/conf/fpathconf.c, so I added musl += conf/fpathconf.o to to the
> Makefile.
>
It's worth thinking whether musl's fpathconf replies with the correct
answers, but perhaps it is indeed good enough.

> Then, the relocater complained about missing inotify_rm_watch. I noticed
> that it's in musl/src/linux/inotify.c, but there are also stubs in
> libc/inotify.cc.
>
The one from musl isn't relevant (and isn't compiled it) because it tries
to call the Linux system call (while this is exactly what we need to
implement).

The stub libc/inotify.cc *should* have been found, but we have a bug - in
include/api/sys/inotify.h we have
    int inotify_rm_watch(int, uint32_t);
But in libc/inotify.cc we have
    int inotify_rm_watch(int fd, int wd)

These don't match, so the second ends up a C++ definition, which gets the
wrong name as you noticed.

To fix this, either include/api/sys/inotify.h or libc/inotify.cc should be
fixed, as appropriate (depending on what is the right type on Linux). Note
that api/sys/inotify.h is a link to musl/, so if we need to change it, we
need to replace the link by a copy.


> I don't know why that wasn't showing up for the relocator, readelf -Ws
> build/release/libc/inotify.o showed _Z16inotify_rm_watchii, but when I just
> added musl += linux/inotify.o to the Makefile, that complained about
> conflicts, so I had to comment out libc += inotify.o. At this point, it
> compiled and ran without crashing. This is the part I don't understand -- I
> would expect the stub inotify_rm_watch to still be visible to the relinker.
>
I'm guessing that your program tries to figure out at run time whether we
have inotify or not. Without inotify.o, you don't have any of its
functions, so the code doesn't use them. With inotify.o, some of these
functions exist correctly, but only inotify_rm_watch is missing.

This makes me think of a problem - we have inotify *stubs* but didn't
actually implement any of these. If the code really relies on inotify
working, it won't work correctly. It seems that removing all these stubs
(removing inotify.o) is better for your program (?) but for other programs
it is better to have these stubs that don't work - so I'm not sure what to
suggest. Of course the last resort is to really implement all these
functions (see https://github.com/cloudius-systems/osv/issues/435) but this
will be a lot of work.


> Anyway, is this the right approach? Pull functions from musl in as needed?
> And, if so, why the inotify stubs instead of just pulling in musl's inotify
> implementation? Sorry if these are n00b questions, I had barely even heard
> of OSv a week ago! Let me know, and I'll try to get a patch prepared and
> sent out.
>
If you look at what musl's inotify implemenetations do, they merely call
syscall() to call the approrpriate system call. In OSv, we need to
*implement* this syscall, not call it :-) That being said, musl's inotify.c
should work in the sense of compiling. It willl just crash (with a missing
system call) if one of these functions is actually used.

Nadav.

**Comment by joelthompson** [comment]
Thanks. To be clear, these aren't really separate issues. I'm just trying to get a very simple Hello, World-style program running which also imports the java.nio library, and these are all the issues I've run in to.

The issues have been with loading the latest JRE's nio shared libraries, and they are crashing due to missing symbols. So when you say, "I'm guessing that your program tries to figure out at run time whether we have inotify or not." It's not my program doing this, it's the JRE which is trying to use inotify, and it's crashing OSv when just loading the shared library because it contains references to the inotify functions and they can't be found during relocation.

Anyway, the issue with the inotify_rm_watch makes much more sense now. And I also see what I think is the cause of the discrepancy between OSv and musl: the [LSB5 definition](http://refspecs.linux-foundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-inotify-rm-watch.html) of inotify_rm_watch specifies the `int inotify_rm_watch(int fd, int wd);` signature (which is in libc/inotify.cc), while the [LSB4 definition](http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib-inotify-rm-watch.html) specifies `int inotify_rm_watch(int fd, uint32_t wd);` (which is in musl/include/sys/inotify.h). While I would favor updating musl to LSB5 standard, I would even more strongly favor not copying musl and making libc/inotify.cc comply with the LSB4 standard.

Thoughts?

**Comment by nyh** [comment]
On Sun, Dec 27, 2015 at 12:29 AM, Joel Thompson <notifications@github.com>
wrote:

> Thanks. To be clear, these aren't really separate issues. I'm just trying
> to get a very simple Hello, World-style program running which also imports
> the java.nio library, and these are all the issues I've run in to.
>

I agree that these are all issues preventing a single program from running,
but it's still useful to have separate issues for each of the problems -
this makes it easier to list the problems still remaining, to track the
progress on fixing the separate problems, and in the future - to have some
history one what we fixed. I'll open an additional bug for the
inotify_rm_watch thing, and perhaps others.

The issues have been with loading the latest JRE's nio shared libraries,
> and they are crashing due to missing symbols. So when you say, "I'm
> guessing that your program tries to figure out at run time whether we have
> inotify or not." It's not my program doing this, it's the JRE which is
> trying to use inotify, and it's crashing OSv when just loading the shared
> library because it contains references to the inotify functions and they
> can't be found during relocation.
>
Ok. What surprised me was your report that if our libc/inotify.cc was not
compiled into OSv, i.e., not only inotify_rm_watch is missing but all
inotify functions are missing - that things are actually better and it
doesn't complain about the inotify_rm_watch(). This led me to guess that
maybe your program (Java...) checks at run time if inotify exists. But I
just looked at the OpenJDK 7 and OpenJDK 8 code, and they do *not* - they
always use inotify on Linux, and I can't find any evidence of a run-time
check for it existing or working. So I don't know to explain how not
compiling libc/inotify.cc into OSv actually improved things.


> Anyway, the issue with the inotify_rm_watch makes much more sense now. And
> I also see what I think is the cause of the discrepancy between OSv and
> musl: the LSB5 definition
> <http://refspecs.linux-foundation.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic/baselib-inotify-rm-watch.html>
> of inotify_rm_watch specifies the int inotify_rm_watch(int fd, int wd);
> signature (which is in libc/inotify.cc), while the LSB4 definition
> <http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib-inotify-rm-watch.html>
> specifies int inotify_rm_watch(int fd, uint32_t wd); (which is in
> musl/include/sys/inotify.h). While I would favor updating musl to LSB5
> standard, I would even more strongly favor not copying musl and making
> libc/inotify.cc comply with the LSB4 standard.
>

The funny thing is that it doesn't even matter which of these we choose -
int and uint32_t have the same length, and any one would work. But what
can't work is the mix we have now (header file says one thing, source code
another thing).

I actually prefer changing inotify.h - taking it from a later version of
musl. I just verified, and newer musl has

int inotify_rm_watch(int, int);

I'll open an issue and submit a patch for this inotify_rm_watch thing.

**Comment by joelthompson** [comment]
OK, thanks -- I've submitted a patch just for __realpath_chk to the mailing list.

**Comment by joelthompson** [comment]
Also, RE: "What surprised me was your report that if our libc/inotify.cc was not compiled into OSv, i.e., not only inotify_rm_watch is missing but all inotify functions are missing - that things are actually better and it doesn't complain about the inotify_rm_watch()."

Sorry, I didn't mean to say that at all, it still complained about inotify_rm_watch. It's purely a matter of which JDK I use.
