### ISSUE TITLE
OSv build on ARM processor

### ISSUE THREAD

**Issue by kkeker** [cloudius-systems/osv#717]
Hello!

Is there a possibility or whether it is planned in the future - OSv run/build on ARM platforms such as Raspberry PI or Hardkernel ODROID?

**Comment by avikivity** [comment]
There is an in-progress ARM port, but it is targeting 64-bit virtualized machines, not 32-bit bare-metal.  It should be possible to extend it, but it is not a trivial amount of work.

**Comment by Michael-Teifel** [comment]
Let me know if you do decide on extending it. I am interested in helping on that project.

**Comment by photoszzt** [comment]
I try to run osv following the aarch64 build instruction on raspberry pi 3 b+ and it hangs at the following line:
```
OSv v0.51.0-8-g78653e6
PSCI: version 0.2 detected.
setup_arm_clock() ENTERED, lr=00000000400d6868
arm_clock(): frequency read as 0000000003b9aca0
interrupt_table::interrupt_table() ENTERED, lr=00000000400a8e44
gic_driver::init_cpu() ENTERED, lr=0000000040207d2c
gic: failed to read cpu mask, assuming uniprocessor
CPU interface enabled.
gic_driver::init_dist() ENTERED, lr=0000000040207d38
number of supported IRQs: 0000000000000120
interrupt table: gic driver created.
 registered IRQ id=0000000000000004
 registered IRQ id=000000000000001b
 registered IRQ id=0000000000000000
smp_launch ENTERED, lr=00000000400d8bc0
 registered IRQ id=0000000000000021
```

I custom build the kernel to 64 bit with kvm support. I want to know how mature the support is after two years since the question is asked.

**Comment by nyh** [comment]
Nothing changed in ARM support in OSv in two years. As @avikivity explained, two groups contributed to aarch64 support in OSv, but both were interested in running on top on hypervisors (KVM and Xen), not on actual hardware. But as far as I can tell from their public participation, both groups appear to have lost interest (or went into stealth mode...). OSv did work to a certain degree, but I think some drivers were not fully working.
You can try putting the application inside the kernel (with scripts/build fs=ramfs) instead of having the kernel trying to read it from the block device (for which a driver is probably missing).
All in all, if you're interested in running OSv on ARM, I can try to help you with specific questions, but you'll have to do most of the debugging and developing yourself. It is possible there will not be a lot of problems (after all, OSv did work on ARM, supposedly) but it's also possible there will be many. 

As for what is not working now - please try to put the application inside the kernel (fs=ramfs) and see if anything improves. If not, you can add printouts in various places or debug (I don't know how) to see where it hangs, and try to figure out why.

**Comment by wkozaczuk** [comment]
Given that OSv support has greatly improved in the last year or so and it is now possible to run OSv on both QEMU in emulated mode (TCG) and KVM and Firecracker on real ARM hardware like RPI 4, Odroid N2, RockPRo64 I am closing this issue. For more details see https://github.com/cloudius-systems/osv/wiki/AArch64#state-of-the-aarch64-port-as-of-jan-2021.
