### ISSUE TITLE
timer assert

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#719]
I'm getting
```
OSv v0.24-58-ge6bf5b8
-2660 < 0, now=-2660

[backtrace]
0x000000000022bc6d <abort(char const*, ...)+249>
0x00000000005c6dde <timer_set<sched::timer_base, &sched::timer_base::hook, osv::clock::uptime>::expire(std::chrono::time_point<osv::clock::uptime, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)+152>
0x00000000005bd07c <sched::timer_list::fired()+56>
0x00000000005bd39a <sched::timer_list::callback_dispatch::fired()+30>
0x00000000005323a2 <???+5448610>
0x0000000000532740 <???+5449536>
0x000000000044c687 <std::function<void ()>::operator()() const+49>
0x000000000048dc29 <interrupt_descriptor_table::invoke_interrupt(unsigned int)+235>
0x000000000048dce9 <interrupt+131>
0x000000000048b8cc <???+4765900>
0x00000000005c4242 <arch::wait_for_interrupt()+8>
0x00000000005b9ea8 <sched::cpu::do_idle()+242>
0x00000000005b9f50 <sched::cpu::idle()+44>
0x00000000005b928e <???+6001294>
0x00000000005c0653 <???+6030931>
0x000000000044c687 <std::function<void ()>::operator()() const+49>
0x00000000005bc8a9 <sched::thread::main()+27>
0x00000000005b9044 <thread_main_c+38>
0x000000000048b8f5 <???+4765941>
0x000000000099ea67 <???+10087015>
0x00000000005bc12b <sched::thread::~thread()+689>
0x458b48b87d894857 <???+2106148951>

```

Code is master@2b04bab + 3 commits. 
Crash happens after VM start, when I http put environment variables into VM - this is before I try to do NFS mount and start openmpi/openfoam app, before trying to start app in new elf namespace.

One thing I'm doing differently than usual is that all VMs have only one IP (so I could run tcpdump to see some other things). But old VM is force-terminated before starting a new one; only one VM should be using that IP at the time.

**Comment by justinc1** [comment]
But maybe, I was starting openmpi or nfs client anyway. Command I started was:
```
mpirun -n 2 -H 192.168.122.1 --launch-agent /home/justin_cinkelj/devel/mikelangelo/osv_proxy/lin_proxy.sh -wd /openfoam/mik3d_15min-2cpu-r5/  /usr/bin/simpleFoam -case /openfoam/mik3d_15min-2cpu-r5/ -parallel
```
Possible is, that while I killed mpirun (from previous trial(s)), lin_proxy.sh on remote host was still up, and just waited to get anyone with right IP to connect to and start nfs client and orted.so (arp cache makes that semi-reliable - I create each VM with uniq/random MAC, but IP is reused).

**Comment by nyh** [comment]
OSv's timer code assumes that osv::clock::uptime::now() non-decreasing. It seems that after the code in timer_list::fired() used _list.expire(now) with now=0, we suddenly went back to now=-2660, and this failed non-decreasing check in timer_set::expire() (timer-set.hh) and crashed.

Some points to think about:

1. We actually have uptime::now() = 0 for quite a bit of time during initialization (see clock-common.cc, how uptime() returns 0 until properly initialized).
2. Presumably, right when uptime::now() stops being 0, it becomes something small and positive. But here we see it became -2660. -2660 is a tiny error - it means 2.6 microseconds. Could this perhaps be an SMP issue - with one vCPU being 2.6 microseconds behind the other one, and because our "boot_systemtime" is global, we end up showing a negative time for one of them? I'll start a discussion on this in the mailing list.
3. It's not clear to me why timer_set::expire() needs to be so unforgiving to timestamp < _last. It is already forgiving to the equally non-useful timestamp == _last, which is good because we have this case for some time during boot (when now() is still 0). So why can't it also forgive timestamp < _last.

**Comment by nyh** [comment]
By the way, @justinc1 can you please confirm that your VMs had multiple vcpus? If it had just a single vcpu, it will rule out my point 2 above from being relevant.

**Comment by tgrabiec** [comment]
@nyh About your question 3 on why timer_set doesn't tolerate time going backwards, it's because the implementation can be simpler if we don't have to handle this case. It would be possible to handle this by rehashing timers already present in buckets - the logic would be a bit different than rehashing when the time goes forward. Not that it'd be hard to do, but it's always some extra complexity.

**Comment by justinc1** [comment]
@nyh yes, I was starting VM with all cpus available on host.

**Comment by nyh** [comment]
@justinc1, is this something which you can reproduce? Will you be able to test a patch?

**Comment by justinc1** [comment]
Cannot reproduce it anymore... And I checked out exactly the same OSv branch (named issue-num), just to keep the state intact. I also run tests with all 8 cpus (4 real, 4 HT). I will close issue, and reopen if it reappears.
