### ISSUE TITLE
DHCP IP is not released at VM shutdown

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#720]
OSv VMs seems to consumed all IP from my DHCP server. In pool is only 50 IPs, but I run only few VMs at any time. I think OSv doesn't release IPs at shutdown?

**Comment by bamboojsr** [comment]
@justinc1 I think this is not OSV's problem, OSV get IP from dhcp,  Maybe this is brctl's probelm.

**Comment by nyh** [comment]
Hi @justinc1,

First, you're right that OSv's DHPC client does **not** currently release the DHCP upon shutdown. Our dhcp.cc is missing the "RELEASE" packet sending code, which can of course be added if required. A slightly uglier complication is that we'll need to *wait* for this release and delay the shutdown until it succeeds. Moreover, any sort of immediate shutdown (including crashes) will miss this step, and leak a lease anyway.

But the second question is should this be considered a bug, or "feature"? Is releasing a DHCP lease on shutdown really required from a guest?

I would like to offer the view (but am open to arguments) that a guest is not really required to release its DHCP lease on shutdown. This is my reasoning:

If the same guest goes up and down, reboots, etc., it will use the next MAC address on the next boot, and will be given the same IP address again. So even a guest which repeatedly reboots will not cause the DHCP server to run out of IP addresses. The DHCP controls (through the lease expiration) how long after a guest shuts down it can receive the same IP address on its next boot.

So the problem becomes what happens in a cloud host which runs many different short-lived guests: If each of the will take an IP address and not return it, the cloud host can run out of available addresses. But I contend that the cloud host really cannot assume that the VM will release its least when shutting down (e.g., a VM might fail without properly shutting down); But the cloud host has other mechanism to know that the guest has shut down - and stopped paying for the service. So the cloud software (like OpenStack) should (?) tell the DHCP server every time that a guest has shut down, so its DHCP can be forcibly released (or tentatively kept only until there is shortage of available addresses).

To return down to earth for a moment, and help you with the specific problem that you had: I think you caused this situation by giving your VM *random* MAC addresses - different random ones on every run. So the DHPC server thinks each VM you start is a completely new client and gives it a different IP address. I am guessing you used random MAC addresses to allow multiple guests to run in parallel; However, for that you did not have to make them completely random - just different. For example, imagine that your test needs 10 different VMs to run in parallel, but it always involves these 10 VMs - you can pick 10 different MAC addresses, but stick to the same 10 MAC addresses every time you run this test; This will give the 10 VMs the same 10 IP addresses every time you run this test.

**Comment by justinc1** [comment]
You are right on all points. Uwe also suggested as workaround to use unique, but not random MAC addresses - use aa:bb:cc:dd:ee:xx, where xx==host ip lowest byte. Enough for 1 VM/host. Replace ee with counter, and then you have N VMs/host.

Problem with this workaround. I know I will start same mpirun command more than once, and accidentally reuse MAC addr from previous run. Unless there will be a central server for MAC addresses :). So it will work, but only as long as you are very careful.

Very short DHCP lease time would help.

Openstack would do more on DHCP server side than simple script I'm using - find some MAC for VM, then set static DHCP IP configuration for that MAC. Sure that MAC - IP mapping is removed once you terminate VM and stop paying for it.

**Comment by bamboojsr** [comment]
As far as know, openstack's orchestrator to adjust VM resource, He has VM's template and call libvirt api. When create vm just replace vm template values. finally update vm resource in Mysql.

**Comment by nyh** [comment]
Something to remember when implementing this:

Quite surprisingly, in the DHCP protocol, when a client sends a DHCPRELEASE packet to the DHCP server, there is no response from the server. This is surprising, which means this feature is completely unreliable, and even if you use it, it might not do anything. 
But nevertheless, we should make our best effort for the DHCPRELEASE to at least go out the network card on time of shutdown. We need to be careful not to sendmsg() the DHCPRELEASE message, and then power off the VM while the message is still in the send buffer or in the network card - before it was actually sent out.

This is the same issue we had in issue #557, where the solution was to use the TIOCOUTQ ioctl to wait until the send queue is empty. That issue was for TCP, and we have a test tests/tst-tcp-siocoutq.cc to test it works correctly, but the present issue is with UDP so we need to confirm that TIOCOUTQ actually works as expected with UDP. I.e., we need to confirm that TIOCOUTQ remains non-zero until the nic acknowledged sending this packet.
