### ISSUE TITLE
Need sigsuspend and openat64 support to run Nginx in OSv

### ISSUE THREAD

**Issue by myechuri** [cloudius-systems/osv#747]
Attempt to start [Nginx OSv](https://github.com/myechuri/osv-apps/tree/nginx-osv/nginx) failed because of missing `sigsuspend` and `openat64` symbols from OSv libc.

```
root@ubuntu:~/osv# scripts/run.py -d
OSv v0.24-101-gc0d25a9
eth0: 192.168.122.15
/tools/nginx.so: failed looking up symbol sigsuspend

[backtrace]
0x000000000022d44f <abort(char const*, ...)+270>
0x0000000000401a46 <elf::object::symbol(unsigned int)+396>
0x000000000040215a <elf::object::resolve_pltgot(unsigned int)+236>
0x000000000040636f <elf_resolve_pltgot+130>
0x000000000048ab15 <???+4762389>
0x0000000000000000 <???+0>
```

Troubleshooting:

```
root@ubuntu:~/osv# scripts/check-libcfunc-avail.sh debug /root/osv/apps/nginx/out/nginx.so
sigsuspend not found
openat64 not found
root@ubuntu:~/osv#
```

Supporting `sigsuspend` and `openat64` would enable running Nginx on OSv.

**Comment by myechuri** [comment]
Picking this up to unblock self.

**Comment by myechuri** [comment]
@rean  ran into the same issue with Nginx 1.10.0.

**Comment by nyh** [comment]
@justinc1 created an unimplemented sigsuspend() symbol in commit 62839c888be763a3afb1051234ae9a6fef04e654 which is enough for running a one-thread nginx because it never actually gets called.
@myechuri produced a full implementation for sigsuspend(). @justinc1 improved on it and sent the result as a patch set titled "sigsuspend implementation" to the OSv mailing list - see https://groups.google.com/d/msg/osv-dev/dEciBlxVmW0/RwZn6klTBgAJ

**Comment by wkozaczuk** [comment]
@nyh shall we close it given `openat64()` is implemented and `sigsuspend()` is not called by nginx? Currently, we can run completely unmodified nginx.
