### ISSUE TITLE
Sigar and (G)LibC

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#752]
Hi folks,

So I'm playing with Kamon, which uses Sigar for OS system metrics. This in turn uses a native libsigar which is typically compiled against Glibc 2.2.5. At least in this instance, it has a symbol called rpc_createerr, which is missing in OSv's LibC (no idea how many other symbols are missing that are expected).

I'll obviously disable sigar for now, but is the usual procedure to add the relevant symbols to libc?

Cheers,

Rowland

**Comment by nyh** [comment]
RPC and XDR are two chunks of the standard C library which implement Sun's Remote Procedure Call and eXternal Data Representation, respectively, which is used mostly (but not exclusively) in implementing NFS (also coming from Sun). Since these APIs were a Sun invention, everybody has mostly been copying Sun's code en-masse: glibc includes one copy, a separate library "libtirpc" has been developed which also builds on a different version of Solaris, and there is even another fork at "libntirpc" (https://admin.fedoraproject.org/pkgdb/package/rpms/libntirpc/).

All these implementations are fairly large chunks of code which we can also copy en-masse, but don't really need to insert into the main OSv kernel - they can be a separate shared library only added when the RPC stuff is needed.

However, some posts I read on the Web suggest that both these RPC codes are complex and have a lot of bizarre dependencies, and they might not be easy to port to OSv. The musl guys suggest a simpler alternative - to use Android's RPC library, which is apparently based on *BSD, and also has a more permissive license than glibc (an Apache license): See here: https://github.com/idunham/libdrpc. Perhaps you can try and see if you can put this libdrpc.so in the image, things will work for you?

Finally, I have no idea if libsigar really depends on RPC, or can work without it. If it can work without it, maybe there is some way we can create stub some of the RPC functions without creating a full implementation. But I don't know if this makes sense (libsigar might actually depends on the RPC functions for sending messages).

**Comment by wkozaczuk** [comment]
@rowlandwatkins are you still interested in pursuing this issue (missing `rpc_createerr`) or shall we close it?

**Comment by wkozaczuk** [comment]
@rowlandwatkins and @nyh I wonder if this issue is still relevant given SUN RPC (`<rpc/rpc.h> headers) was removed from glibc (see https://sourceware.org/pipermail/libc-announce/2020/000029.html):
```
Deprecated and removed features, and other changes affecting compatibility:

* Remove configure option --enable-obsolete-rpc.  Sun RPC is removed
  from glibc.  This includes the rpcgen program, librpcsvc, and the Sun
  RPC header files.  Backward compatibility for old programs is kept
  only for architectures and ABIs that have been added in or before
  glibc 2.31.  New programs need to use TI-RPC
  <http://git.linux-nfs.org/?p=steved/libtirpc.git;a=summary> and
  rpcsvc-proto <https://github.com/thkukuk/rpcsvc-proto>.
```

BTW I have just created a somewhat related (Sun RPC deprecation) issue - #1162. 

On top of this [libsigar](https://github.com/hyperic/sigar) seems to have gone stale (no commits in last 5 years) so we really care at this point? I think even if something else needs some kind of RPC library they would use "libtirpc", "libntirpc" or https://github.com/idunham/libdrpc.

Shall we close it?

**Comment by nyh** [comment]
I'll close it. I haven't seen Sun RPC for about 20 years, and I don't think it's going to make a comeback ;-) If anybody will ever want to use Sun RPC on OSv they will just have to do what they do on Linux - namely use some external library.
