### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by ufo19890607** [cloudius-systems/osv#764]
Hi everyone,
I am a new fish here. I have ever read some micro-kernels' codes, eg. seL4 .Could you give me some tips about how to start reading osv's code?  Do you have any integrated manual references or technical documentations about osv?

**Comment by nyh** [comment]
I see that you later found the OSv mailing and wrote your question there, so that was a good start :-) See Dor pointed you to the OSv Usenix paper, which is indeed a good introduction to the design of OSv.
If you have more questions, you are welcome to ask on the OSv mailing list (this bug tracker is for bug reports and feature requests - not questions and discussions).
