### ISSUE TITLE
Integrate Apache Portable Runtime native library with OSv

### ISSUE THREAD

**Issue by tgrabiec** [cloudius-systems/osv#77]
Tomcat's performance could benefit from it. See http://tomcat.apache.org/tomcat-7.0-doc/apr.html

**Comment by geraldo-netto** [comment]
Hi Guys,

there is a plan to deprecate APR as you can see here:
http://people.apache.org/~markt/presentations/2018-09-24-state-of-the-cat.pdf

Maybe we should close this ticket?


Kind Regards,
Geraldo Netto

**Comment by nyh** [comment]
This presentation says this is a plan for the future - but current versions do use it. So I don't we should close this issue, but we should definitely give it very low priority, because it's just for one application - Tomcat. Someone who cares about Tomcat (you?) should check again whether APR still doesn't work. Maybe it does - the last time anyone tried to run this was 4 years ago (!) and we added many missing functions since.

**Comment by wkozaczuk** [comment]
As some have noted above, this issue seems irrelevant at this point in history so I am closing it.
