### ISSUE TITLE
gdb "osv info threads" stopped working, and so did "make check"

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#772]
The load_thread_list() code in scripts/loader.py stopped working on recent distributions (saw the same problem on both an updated Fedora 23, and a Fedora 24):
```
(gdb) osv info threads
Traceback (most recent call last):
  File "/home/nyh/tmp/osv/scripts/loader.py", line 912, in invoke
    state = vmstate()
  File "/home/nyh/tmp/osv/scripts/loader.py", line 769, in __init__
    self.reload()
  File "/home/nyh/tmp/osv/scripts/loader.py", line 773, in reload
    self.load_thread_list()
  File "/home/nyh/tmp/osv/scripts/loader.py", line 785, in load_thread_list
    threads = map(gdb.Value.dereference, unordered_map(gdb.lookup_global_symbol('sched::thread_map').value()))
AttributeError: 'NoneType' object has no attribute 'value'
Error occurred in Python command: 'NoneType' object has no attribute 'value'
```

This breaks the "osv info threads" command in gdb, and also one of the tests in "make check".

My guess is that the "unordered_map" class in scripts/loader.py stopped working when a recent libstdc++  improvement changed some internal detail of std::unordered_map's implementation.

**Comment by enixdark** [comment]
On 24 Jul 2016 04:44, "nyh" <notifications@github.com> wrote:

The load_thread_list() code in scripts/loader.py stopped working on recent
distributions (saw the same problem on both an updated Fedora 23, and a
Fedora 24):

(gdb) osv info threads
Traceback (most recent call last):
  File "/home/nyh/tmp/osv/scripts/loader.py", line 912, in invoke
    state = vmstate()
  File "/home/nyh/tmp/osv/scripts/loader.py", line 769, in __init__
    self.reload()
  File "/home/nyh/tmp/osv/scripts/loader.py", line 773, in reload
    self.load_thread_list()
  File "/home/nyh/tmp/osv/scripts/loader.py", line 785, in load_thread_list
    threads = map(gdb.Value.dereference,
unordered_map(gdb.lookup_global_symbol('sched::thread_map').value()))
AttributeError: 'NoneType' object has no attribute 'value'
Error occurred in Python command: 'NoneType' object has no attribute 'value'

This breaks the "osv info threads" command in gdb, and also one of the
tests in "make check".

My guess is that the "unordered_map" class in scripts/loader.py stopped
working when a recent libstdc++ improvement changed some internal detail of
std::unordered_map's implementation.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cloudius-systems/osv/issues/772>, or mute the thread
