### ISSUE TITLE
Potential race condition

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#782]
This issue is the result of a thought experiment while analyzing issue #779 - I don't have any evidence that it is an actual problem.

It is possible that a thread went into a "waiting" state, and before actually yielding it cancels its wait (because it notices the criterion it wanted to wait for was already true). What if somebody wakes this thread between these steps (between prepare_wait() and stop_wait())? Normally this would be fine - at worst it would be a spurious wakeup. But what if the thread that stopped waiting decides to exit? The thread object will be destroyed, causing the wakeup queue this thread is in to be messed up (it uses the thread's "_wakeup_link" for linking) and also code in handle_incoming_wakeups() which tries to use "t" can crash.

**Comment by enixdark** [comment]
On 8 Aug 2016 19:19, "nyh" <notifications@github.com> wrote:
>
> This issue is the result of a thought experiment while analyzing issue
#779 - I don't have any evidence that it is an actual problem.
>
> It is possible that a thread went into a "waiting" state, and before
actually yielding it cancels its wait (because it notices the criterion it
wanted to wait for was already true). What if somebody wakes this thread
between these steps (between prepare_wait() and stop_wait())? Normally this
would be fine - at worst it would be a spurious wakeup. But what if the
thread that stopped waiting decides to exit? The thread object will be
destroyed, causing the wakeup queue this thread is in to be messed up (it
uses the thread's "_wakeup_link" for linking) and also code in
handle_incoming_wakeups() which tries to use "t" can crash.

**Comment by nyh** [comment]
This race condition does not exist: wake_impl() only adds the thread to the wakeup queue if it managed to atomically change status::waiting to status::waking. If it did, then thread::stop_wait() will not be able to cancel the wait: It would not be able to atomically change status::waiting back to status::running, so it will call (in a loop) cpu::schedule() to wait until the wakeup happens - so the thread cannot exit before it does.
