### ISSUE TITLE
OSv-Tomcat Instance initiated shutdown on EC2 whilst running a Tomcat Application

### ISSUE THREAD

**Issue by HarryHarcourt** [cloudius-systems/osv#806]
Hi - sorry I am very new to this but super excited with this project!
I pulled the OSv-Tomcat AMI and started and instance in EC2
I installed a WAR file from the Essential Project [(enterprise-architecture.org)](http://www.enterprise-architecture.org/) and then uploaded my "EA Meta Data".
The application seems to work fine but if I go into an area I note that the CPU goes to 100% and the OSv starts shutting down.
With no logs it is a challenge to know where to start, on EC2 the reason reported is that the OS initiated the shutdown.
How can I troubleshoot this further?  What else would you like from me to help?
Best

**Comment by HarryHarcourt** [comment]
Update - 
Went through the tomcat logs and and found no warnings or errors prior to shutdown.
Went through dmesg, again no joy, any pointers would be good.

**Comment by wkozaczuk** [comment]
Which JDK is it? What is an OSv version.

I suspect you picked quite old version which was built in December last
year.

Have tried to build it from master and then create AMI to see if it works?

Also you can try to enable JMX, connect and capture thread dump.

Waldek

**Comment by HarryHarcourt** [comment]
Hi Waldek
Thanks so much for answering, as I stated I am very excited about this and any UniKernel project (however from a System Admin point of view I think OSv this is easiest to understand).
Getting the information you requested:
"v0.24"
JVM Version	1.7.0_55
In relation to the last two questions, pending a new laptop which will enable me to make / build (going through transistion at the moment).
The challenge I have with thread dumps is that they are good to look at something before and after.  The challenge I have is that there is no after.  I do X and simply the OSv instance shuts down and I don't know how to see what triggers that.
Many thanks
Ben

**Comment by nyh** [comment]
Our last "released" version, and AMI, is already one year old (@penberg, for your consideration!), so as @wkozaczuk said, it might be a problem that was already solved, but it can also be something very different.
By default, when OSv crashes on a bug, it does not initiate a clean shutdown, but rather hangs (so you can connect to it and see some messages on the console). If something did initiate a clean shutdown, I guessing it was the Java code which called exit(), possibly because it encountered some application error or perhaps something which it expected OSv to support, but didn't. 
But you looked at the console output (I hope EC2 saves that), and the logs (stored inside the image, do you know how to fetch them?) and didn't see any error or exception or anything before the shutdown?

**Comment by HarryHarcourt** [comment]
Gents
With the goal of immutable infrastructure I tore down the OSv image with the goal of standing it up again, I am learning and moving towards improving the log level within Tomcat (for some reason now I cannot put a new logging.properties file in place). 
It is funny, I did not see the EC2 console screen, but I will say again that the OSv image did actually shutdown and not hang which could point to an issue with the Java code or OSv support issue.
Please close this for now, as I work through this I will get more pertinent information to help fix the issue at hand.  As I said I think the unikernel projects are the right direction for "systems" to go - please keep up the good work.
Best
