### ISSUE TITLE
cloud-init sometimes causes NFS mount to fail due to DHCP IP release

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#816]
Recent changes in cloud-init (964166756c134dd21b7bd626f8cc2dc3c63d5bcd and 0593bcde9d1651d0d99856b4b22f4005218cb536) are likely cause of problem below.
```
OSv v0.24-240-gd3f1bcf
eth0: 172.18.2.233
Error in mount(): I/O error(5)
Error in mount(): Operation not permitted(1)
eth0: 172.18.2.233
```

OSv wants to send its new name to DHCP server, and to do this, it does DHCP release, followed by new DORA cycle. For short time, VM has no IP, and NFS mount fails.

**Comment by justinc1** [comment]
I was thinking about not doing release + DORA, but only sending out new DHCP request with updated name. It is legal (essentially it is an early renew). Then, it is up to the DHCP server to take new hostname into account or not. But also in original request, DHCP server might decide to ignore the client provided hostname.

A very short test against dnsmasq shows this works, just as good as release+DORA. I will test that against isc-dhcpd-4.1 on our LAN too.

**Comment by nyh** [comment]
Yes I agree. As we both noted several times already, the "release" step in the DHCP protocol is completely optional - and must be optional because it is not reliable (e.g., the packet can be lost). There was some reasoning to do a release when a VM goes down, but no real reason to do a release in this case.
So I agree, no reason to release in this case.

**Comment by wkozaczuk** [comment]
The commit d9649db10894e74e7e8c1a55e01e5b0758808f9a broke DHCP logic on VMware. I identifed it by testing builds right before and after this patch. It might not be VMware related by instead specific to particular DHCP server behavior. In any case OSv never gets (or processes) packet DHCP_MT_ACK from DNS server that returns IP address so it stays in this infinite loop:

[I/27 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: dhcp-10-191-57-252

[I/27 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: dhcp-10-191-57-252

[I/27 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: dhcp-10-191-57-252

[I/27 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: dhcp-10-191-57-252 

I think these 2 log lines pop-up every 1-2 seconds.

Before this patch the relevant log would show this:

 [I/27 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: dhcp-10-191-57-252

[I/195 dhcp]: DHCP received hostname: osv.local

[I/195 dhcp]: Server acknowledged IP for interface eth0
[I/195 dhcp]: Configuring eth0: ip 10.191.57.252 subnet mask 255.255.255.0 gateway 10.191.57.1 MTU 1500
[I/195 dhcp]: DHCP received hostname: osv.local

**Comment by justinc1** [comment]
Must be my fault :/

dhcp_interface_state::process_packet is called, and dm.decode() at https://github.com/cloudius-systems/osv/blob/7ac0b4dbd3fb909536274204c19929f14c6f41a2/core/dhcp.cc#L566 logs "DHCP received hostname" . Then, I guess  state_discover() is not called because _state != DHCP_DISCOVER.

I will try to add some additional log lines and reproduce this. But I have to first find some VMWare machine. @wkozaczuk is free esxi good enough to reproduce this? Or alternatively, maybe I can run only their DHCP server. Do we know which DHCP server do the use (I expect they have their own implementation, but it still worth to ask)?

**Comment by wkozaczuk** [comment]
I have been testing it on VMware ESXi 6.0. I am not sure if you can use
free version.

The DNS server is infoblocks (https://www.infoblox.com/).

I am more than happy to apply your logging patches to dhcp.cc so that we
can gather more info.

Thanks for your help,
Waldek

**Comment by justinc1** [comment]
A fellow has a semi-production vmware server, and I plan to run OSv vm on it. So hopefully we will not need to ping-pong patches and cosole logs :). I will do that  probably on Monday.

**Comment by wkozaczuk** [comment]
After adding debug info and more research it turns out is that the issue is NOT VMware related. Instead it has to do with how strict some DHCP servers are. It turns out the the culprit is this fragment of the patch:

         pkt->secs = 0;
         pkt->flags = 0;
         memcpy(pkt->chaddr, IF_LLADDR(ifp), ETHER_ADDR_LEN);
+        ulong yip_n = htonl(yip.to_ulong());
+        ulong sip_n = htonl(sip.to_ulong());
+        memcpy(&pkt->ciaddr.s_addr, &yip_n, 4);
 
         // Options
         u8* options_start = reinterpret_cast<u8*>(pkt+1);
@@ -242,7 +244,7 @@ namespace dhcp {
         *options++ = DHCP_OPTION_END;
 
         dhcp_len += options - options_start;
-        build_udp_ip_headers(dhcp_len, INADDR_ANY, INADDR_BROADCAST);
+        build_udp_ip_headers(dhcp_len, yip_n, sip_n);

This patch makes method dhcp_mbuf::compose_request() used in both RENEWING and SELECTING phase. The latter requires REQUEST packet to broadcast per RFC. 

Anyway I am in the process of testing a patch to this issues and I should be sending new one soon.

**Comment by justinc1** [comment]
Thank you for doing this @wkozaczuk. I will then not continue with fixin my patch (unless I made to big mess, and you decide that maybe whole d9649db requires rewrite or something like that).

**Comment by nyh** [comment]
@justinc1 @wkozaczuk let's not hijack a closed issue to discuss a bug which is still open. I'll open a new issue for this.
