### ISSUE TITLE
Migrate interrupts closer to the thread that uses them

### ISSUE THREAD

**Issue by avikivity** [cloudius-systems/osv#82]
I had some code that migrates MSI interrupts to the cpu that is running the thread that services those interrupts.  Need to resurrect it.

**Comment by wkozaczuk** [comment]
I wonder if this issue was addressed by some commit that added this code to msi - https://github.com/cloudius-systems/osv/blob/cb7d1803d5e531d75454d62e235b3537abb9f061/arch/x64/msi.cc#L96-L130. Seems to be checking if the vector handler is on the cpu the affinity was set to and migrates it to that cpu if not.

Here is the commit from Feb 11, 2014 after this issue was created - https://github.com/cloudius-systems/osv/commit/b4e8d47d5eed133f4460aa72fe60a15400386ed4. So maybe this code was "resurrected" as @avikivity mentions above.

**Comment by avikivity** [comment]
Seems likely.
