### ISSUE TITLE
undefined reference to __gthrw_pthread_mutex_lock on ubuntu14.04, centos7

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#823]
After c1c6939dec9ff6b74e13743d45598a56396553f0 following error is reported on both ubuntu14.04 and centos7:
```
[xlab@mike-c7 osv]$ make mode=debug -j4
Building into build/debug.x64
  GEN gen/include/osv/version.h
  CXX libc/pthread.cc
  LINK loader.elf
build/debug.x64/libc/pthread.o: In function `__gthread_mutex_lock':
/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-default.h:748: undefined reference to `__gthrw_pthread_mutex_lock(pthread_mutex_t*)'
build/debug.x64/libc/pthread.o: In function `__gthread_mutex_unlock':
/usr/include/c++/4.8.2/x86_64-redhat-linux/bits/gthr-default.h:778: undefined reference to `__gthrw_pthread_mutex_unlock(pthread_mutex_t*)'
make: *** [build/debug.x64/loader.elf] Error 1
```

This happens only for mode=debug, release build still works. Fedora 25 build is not broken.

**Comment by nyh** [comment]
Indeed I can't reproduce this on Fedora 25 and gcc 6.2.1.

All this __ghtread* stuff is part of the C++ header files (which OSv does not change). For it own internal uses, libstdc++ has has a lot of static inline functions like
```c++
__gthread_mutex_lock (__gthread_mutex_t *__mutex)
{
  if (__gthread_active_p ())
    return __gthrw_(pthread_mutex_lock) (__mutex);
  else
    return 0;
}
```

The macro __gthrw_(pthread_mutex_lock)  may expand to __gthrw_pthread_mutex_lock, but if that is the case, the same header file (gthr-default.h) is also supposed to define this symbol, with
``` c++
# define __gthrw2(name,name2,type) \
  static __typeof(type) name __attribute__ ((__weakref__(#name2))); \
  __gthrw_pragma(weak type)
#define __gthrw(name) __gthrw2(__gthrw_ ## name,name,name)
__gthrw(pthread_mutex_lock)
```

I.e., __gthrw_pthread_mutex_lock is supposed to be a weak symbol for pthread_mutex_lock - it should NOT be an undefined reference... I'm not sure how to continue debugging this, because I don't have access to gcc 4.8 at the moment.

I think this commit exposed this issue because it includes <osv/latch.hh> which, uncharacteristically of other OSv code, uses std::mutex, and thus libstdc++'s posix threads stuff and in particular that __gthr* stuff.

**Comment by nyh** [comment]
Looking at the output of `nm -C osv/build/debug.x64/libc/pthread.o | grep pthread mutex_lock` on Fedora 25 (where this problem does not exist), I see:
```
0000000000001088 t __gthrw_pthread_mutex_lock(pthread_mutex_t*)
0000000000001088 T pthread_mutex_lock
```
So while pthread_mutex_lock is a global symbol defined in pthread.cc, __gthrw_pthread_mutex_lock(pthread_mutex_t*) is a local symbol, as expected, and not undefined (U).
What do you see on your older distro as the output of this nm command?

**Comment by justinc1** [comment]
centos7
```
[xlab@mike-c7 osv]$ nm -C build/debug.x64/libc/pthread.o | grep pthread_mutex_lock
000000000000117b T pthread_mutex_lock
                 U __gthrw_pthread_mutex_lock(pthread_mutex_t*)
```

ubuntu 14.04
```
xlab@ompi-1:/home/justin_cinkelj/devel/mikelangelo/osv-ub1404$ nm -C build/debug.x64/libc/pthread.o | grep pthread_mutex_lock
000000000000117b T pthread_mutex_lock
                 U __gthrw_pthread_mutex_lock(pthread_mutex_t*)
```

**Comment by nyh** [comment]
This is so puzzling. You say that in the release build, the compilation works. What does the "nm" command of above produce in the release build?

I ran the C preprocessor on the gthr.h, with
```
/home/nyh/osv$ c++  -Iinclude/api -Ibuild/release/gen/include -Iinclude/api/x64 -E /usr/include/c++/6.2.1/x86_64-redhat-linux/bits/gthr.h
```
(I checked that the gthr.h and related header files didn't change since gcc 4.8 which you use; note that this command line uses), and see the following relevant lines:

```c++
extern "C" {
int pthread_mutex_lock(pthread_mutex_t *);
}
static __typeof(pthread_mutex_lock) __gthrw_pthread_mutex_lock __attribute__ ((__weakref__("pthread_mutex_lock")));
```

So why doesn't that properly define  __gthrw_pthread_mutex_lock - and why does debug mode change anything?

**Comment by justinc1** [comment]
On centos 7
```
[xlab@mike-c7 osv]$ nm -C build/release.x64/libc/pthread.o | grep pthread_mutex_lock
0000000000000ca0 T pthread_mutex_lock
[xlab@mike-c7 osv]$ 
```

**Comment by nyh** [comment]
This smells like a compiler bug. We have here a very special situation: The same source file both uses pthread_mutex_lock through all the weak-reference trickery (so far, normal), but, also, *defined* this same function. This is not a normal occurance. Normal programs use this trickery, but do not redefine pthread_mutex_lock.

Here is a simple C++ program which does something similar to what I saw with pthread_mutex_lock:

```c++
extern "C" {
int incr(int i);
}
static __typeof(incr) incr_alias __attribute__ ((__weakref__("incr")));
int incr(int i) {
    return i + 1;
}
#include <iostream>
main(){
    std::cout << incr_alias(1) << "\n";
}
```

When compiled without optimization (it doesn't matter if "-g" is actually used), e.g., c++ -c x.cc, on Fedora 25, I see
```
nm -C x.o| grep incr
000000000000007b t _GLOBAL__sub_I_incr
0000000000000000 t incr_alias(int)
0000000000000000 T incr
```
But when compiled with optimization, e.g, ,c++ -O2 -c x.cc (even -O1 is enough),
```
0000000000000030 t _GLOBAL__sub_I_incr
0000000000000000 T incr
``` 
So with optimization, the alias "incr_alias" is "optimized away" and doesn't get a symbol; but without optimization, it remains, as a local symbol, "t". But both are fine. This is very similar to what I see with the pthread_mutex_lock stuff.

What would *not* be fine is if we were to see "U" (undefined symbol) instead of "t". Or if "c++ x.cc" would fail linking with a missing symbol. Does any of this happen with gcc 4.8.2.? @justinc1 can you please check?

If this turns out a real compiler bug, since we do want to support 4.8.2 (even though it is ancient), ,I think the workaround we'll need is not to define pthread_mutex_lock() in the same source file using std::mutex. I.e., we can't use std::mutex in pthread.cc. So we need to modify latch.hh (which pthread.cc now includes) to use OSv's "mutex" and "condvar", not std::mutex and std::condition_variable.

**Comment by justinc1** [comment]
```
[xlab@mike-c7 issue-823]$ gcc -v
...
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC

[xlab@mike-c7 issue-823]$ c++ -c x.cc -O2
[xlab@mike-c7 issue-823]$ nm -C x.o| grep incr
0000000000000030 t _GLOBAL__sub_I_incr
0000000000000000 T incr
[xlab@mike-c7 issue-823]$ c++ x.o
[xlab@mike-c7 issue-823]$ ./a.out 
2

[xlab@mike-c7 issue-823]$ c++ -c x.cc
[xlab@mike-c7 issue-823]$ nm -C x.o| grep incr
000000000000007a t _GLOBAL__sub_I_incr
0000000000000000 T incr
                 U incr_alias(int)
[xlab@mike-c7 issue-823]$ c++ x.o
x.o: In function `main':
x.cc:(.text+0x19): undefined reference to `incr_alias(int)'
collect2: error: ld returned 1 exit status
```

So this is exactly what you suspect.
