### ISSUE TITLE
cloud-init started before httpserver

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#830]
In console is:
```
Running from /init/00-cmdline: /usr/mgmt/cloud-init.so;

Running from /init/30-auto-00: /libhttpserver.so &!
```

Is this a potential problem? Cloud-init might use httpserver (to upload files, run app, mount NFS).
If port 8000 is not opened yet, then TCP SYN will be rejected. Would cloud-init retry action in such case?

**Comment by nyh** [comment]
This order was done deliberately, in commit 65b21aac2df285e43db09aaad74dad3d86dcca06 "cloud-init: run before httpserver"

The rationale was that cloud-init might configure things for httpserver.

Does cloud-init really need to use httpserver? Why? Why does it need httpserver to run an app or mount NFS or any of the other examples you gave? I don't know the answer to the question "would cloud-init retry action in such case", because I don't know why cloud-init needs to contact httpserver.

Note that in any case, running httpserver "before" cloud-init is tricky, because httpserver runs in the background - even if we start it before, it can take time until it actually accepts connections.

**Comment by justinc1** [comment]
So order is intentional. Looking at wiki I see now that httpserver port and SSL are configurable.
But example includes also:
```
run:
    - PUT: /file/usr/log
      op: MKDIRS
      permission: 0777
```
And already that requires httpserver to be up, right?

**Comment by nyh** [comment]
I don't know what this syntax means, or how it was was supposed to work (it can't work now, because cloud-init starts, and finishes, before httpserver ever starts). Theoretically, since cloud-init is a fully capable piece of code it can do whatever it wants itself, without resorting to making a connection to the internal HTTP server to ask it to do something.... I don't know who wrote this example in the wiki, and if it's a really useful example...

If there's something that **you** are trying to do and the current order is preventing you from doing, let's discuss your use case.

**Comment by justinc1** [comment]
Watching behavior more carefully - here and then, the cloud-init mount: section doesn't have effect. No error in OSv console, no error in NFS server log. I guess that's because failed attempt to run mount-nfs.so command is silently ignored.

But with run section like:
```
run:
  - GET: /os/version
  - PUT: /app/
    command: "/usr/bin/udpping.so 192.168.122.1 3333 5 500"
```
and with udpping.so intentionally missing, I didn't notice ever missing error about "Failed to load object: /usr/bin/udpping.so".

So the easy way -  I just add additional GET before trying to run mount-nfs.so. Or maybe we can think about more generic solution?

**Comment by nyh** [comment]
I'm afraid that I am not familiar enough with cloud-init or its syntax to understand what you're trying to do. What does "adding an additional GET" could possibly solve, considering that we determined that the HTTP server is not running at the time this GET is done?

Maybe we should close this issue and instead open a new one which explains an actual problem - some case where mount isn't working, or something - and why this case needs (!?) an http server to work?

**Comment by justinc1** [comment]
> mount and why this case needs (!?) an http server to work
It needs http just because that is how I implemented mount in cloud-init. I could run binary without http. BUT there were/are already other cloud-init modules which use http!

If all wiki examples would include server IP, I would say I missed detail that API calls are intended to be used for interaction with other VMs (not with localhost).

> HTTP server is not running at the time this GET is done
And still cloud-init is (often) able to use it. The run and mount sections usually works. And they wait for response and check for HTTP 200 code.
```
/init# cat 00-cmdline
/usr/mgmt/cloud-init.so;

/init# cat 30-auto-00
/libhttpserver.so &!
```
So cloud-init should finish before httpserver is even started. Maybe this is actually different? Then setting httpserver configuration via cloud-init is/would-be broken.

I think that in my comment above, I misunderstood the effect of run section. I guessed that maybe suctions are run in parallel. But osvinit::do_yaml() https://github.com/cloudius-systems/osv/blob/master/modules/cloud-init/cloud-init.cc#L313 processes config sequentially, and exits on first error (if halt_on_error is set). Based on that, I would expect repeatable result - if a problem occurs (like missing app in run section) before the mount section, than mount will never be even tried. But it is tried - often, but not always. And mount_module::do_api does check for HTTP 200 return code - https://github.com/cloudius-systems/osv/blob/master/modules/cloud-init/cloud-init.cc#L240 (but that would catch only missing mount-nfs.so binary).

**Comment by nyh** [comment]
In loader.cc, see "if (opt_init)", we look at the files in /init in alphabetical order, so unless something is broken in this code, we read 00-cmdline first, and then 30-auto-00. You can run with -V to see debugging messages on what is being run.
These files are read and inserted into the of commands - which we then run in order.
If that actually happens as expected, we should be running cloud-init.so and waiting for it to complete (the code calls app->join()) and only then libhttpdserver.so should be started... You can add more printouts to check if this is NOT what happens.

It is possible, but I have no idea if this actually happens (I'm not at all familiar with this part of OSv), that cloud-init.so acts like a UNIX daemon, in the sense that it starts a new thread to do some background work - and then the original thread returns and pretends the command finished. If this is what happens, it might explain why it seems that cloud-init runs in parallel with libhttpserver.

I'm afraid I didn't understand the last paragraph in your comment. 

At this point, I think you understand the cloud-init stuff better than I do, so please feel free to suggest any sort of change - even reverting 65b21aac2df285e43db09aaad74dad3d86dcca06 - if you can explain your proposal.

**Comment by nyh** [comment]
It seems there's a lot in our cloud-init code I don't understand... Maybe @amnonh @tgrabiec or @penberg can fill in a few blanks.

I looked a bit at modules/cloud-init now, and It appears that beyond the stand-alone httpserver being run, the cloud-init module is also *linked* with the libhttpserver library, ! So cloudinit runs httpserver itself,  I presume at the right time, before it needs it. I don't know why we start an additional httpserver, if that even happens (maybe httpserver has code to guarantee only one runs - I see it has a concept of "global_server"). So clearly I didn't understand until today how cloud-init and httpserver interact... I'm still not sure I understand...

But more importantly, can you please clarify what problem this issue is about? What doesn't work?

**Comment by justinc1** [comment]
The problem I see here and there is that NFS mount is not mounted. I will repeat more tests, with printf lines added, to make sure that really no mount attempt was made. It could be that mount was tried, but failed silently.

Sure, that NFS-not-getting-mounted problem is different than issue title. When I opened issue, I just wanted to check if "cloud-init before httpserver" order is intentional, as it seemed to me that it could cause problems.

**Comment by benoit-canet** [comment]
Justin,

you should know that the nfs mount is lazy if I remember correctly.

It just says nothing and does the real mounting works at first disk access.

**Comment by justinc1** [comment]
There is a bit of real NFS activity when mount-nfs.so is started, as I get in server logs:
```
Jan 16 16:42:05 jcpc.xlab.lan rpc.mountd[3936]: authenticated mount request from 192.168.122.203:53524 for /ggg (/ggg)
```

Otherwise yes, when openning (first?) file, a second "authenticated mount request" is logged. Thank you for remanding me about that.

**Comment by nyh** [comment]
@justinc1, can we close this bug? I'm not sure what is the actual problem that we need to solve here...

**Comment by justinc1** [comment]
Can be closed. I would say I just could didn't understand how is possible that cloud-init uses httpserver via REST api (as you said, cloud-init is also linked with libhttpserver.so, so that should be the trick), and was then worried that use of REST in cloud-init might sometimes fail.
