### ISSUE TITLE
Http server does not handle preflighted requests correctly 

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#832]
Per CORS specification (described how it works here - https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) the so called preflighted requests (with method OPTIONS) are handled incorrectly by httpserver.

Currently the OPTIONS requests are treated as corresponding DELETE, PUT requests and as such result in 400 access code. Instead OPTIONS requests should simply be handled by return corresponding CORS response headers that allows client to issue follow-up DELETE or PUT request for example.

**Comment by nyh** [comment]
I'm not familiar with this "CORS" thing, but the "OPTIONS" method is actually described in the HTTP 1.1 RFC (https://tools.ietf.org/html/rfc2616#section-9.2).

Note that "OPTIONS" is new to HTTP 1.1. It did not exist in HTTP 1.0 (see https://tools.ietf.org/html/rfc1945). We have a potential problem here: I think our httpserver is pretending to be 1.0, not 1.1...
I think, though, it is safe for httpserver, even if it pretends to be HTTP 1.0 in its responses, to accept HTTP 1.1 requests. Since we're more than 20 years (!!) after HTTP 1.0 was released, I think it's time we support HTTP 1.1 ;-)
