### ISSUE TITLE
per-module search path

### ISSUE THREAD

**Issue by avikivity** [cloudius-systems/osv#84]
If shared object x brings in shared object y, other objects shouldn't necessarily see it.

We probably need a DAG that describes which modules are visible from other modules.

**Comment by nyh** [comment]
We  already have support for this feature, as "ELF namespaces", enabled (for example) by setting new_program=true in osv::run(). Our existing support needs to be explicitly enabled - the user decides which set of objects is seperated in a separate "application" or "ELF namespace" which other sets.

Avi's suggestions of doing this implicitly (if object X required Y, but a third object Z did not require Y then Y will not see functions from Z) make a lot of sense. But I am worried that this is not how things work in Linux so it might result in some complex applications not working because a late-loaded library (e.g., dlopen) will not see previously loaded libraries that it did not bother to explicitly require because things just worked on Linux.

**Comment by wkozaczuk** [comment]
@nyh Shall we close it given your comment about ELF namespaces and the fact, that implementing what Avi described, would make it incompatible with Linux?

**Comment by nyh** [comment]
I guess so. This explanation should be mentioned in some documentation somewhere (I don't know where...) and can always be found in the bug tracker under closed issues, but it shouldn't be an open issue if we don't want to do it. So closing.

**Comment by wkozaczuk** [comment]
@nyh There is a new wiki page I created to describe how OSv dynamic linker works but it lacks a lot so it might be a good place to add these details and polish it more - https://github.com/cloudius-systems/osv/wiki/Dynamic-Linker

**Comment by nyh** [comment]
> @nyh There is a new wiki page I created to describe how OSv dynamic linker works but it lacks a lot so it might be a good place to add these details and polish it more - https://github.com/cloudius-systems/osv/wiki/Dynamic-Linker

Another important source to mention in your new document is https://akkadia.org/drepper/tls.pdf
There's a huge amount of explanations that can still be written in that document, I guess we'll need to take one step at a time...
