### ISSUE TITLE
gethostid missing

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#841]
The gethostid implemented in musl always returns 0. The vampirtrace uses the value to differentiates between multiple hosts. It checks that number is non-0, and complains if it is 0. So a proper implementation is required.

For now I use code in lib.cc like:
```
long gethostid()
{
    static long hostid = 0;
    if (hostid == 0) {
        hostid = random();
    }
    return hostid;
}
```

Good enough or not? Per man page, ethernet MAC should be used. But when the same image is re-booted with different MAC addr, the ID would change (so in visualized case, this is not that constant as it was N years ago).

ID (being random number or MAC) could be written to a file. But same image can be cloned N times, and duplicated IDs are bad.

http://man7.org/linux/man-pages/man3/gethostid.3.html

**Comment by nyh** [comment]
What a mess...

I can think of two "reasonable" alternatives for what to do with gethostid():

1. On boot, read from /etc/hostid and call sethostid() with what we read, but if this file doesn't exist, pick a random id (e.g., from /dev/urandom if we do this late enough in the boot).
2. On boot, sethostid() with a 32-bit digest of the mac address.

Option 1 is messy on VMs if you're cloning an image which already ran and picked a hostid. It's not a problem if the user clones the image before it ever ran - but since we do run the image once during build we at least need to make sure that this build run does not set the id (upload_manifest.py already uses --norandom, --nomount, --noinit, and can pass another option, or re-use the "--noinit" option).

I think option 2 is cleaner. But you're suggesting that maybe we have a problem that rebooting the same VM will come with a different MAC address. On this I have two questions: 1. Do regular clouds give you a different MAC address every time you boot? 2. Do we care, i.e., shouldn't we actually consider the rebooted machine a new machine?

I don't know what is the best option here. I think we should simply do what Linux does here. On my Fedora there is no hostid saved anywhere in /etc, so I'm guessing it just uses the MAC address. If so, we should do the same?

**Comment by benoit-canet** [comment]
I think too a digest of the mac address is safer.

**Comment by justinc1** [comment]
Ok, so lets use MAC address. I think using first AF_PACKET type iface with non-zero MAC (to skip loopback) should be ok. To get 32 bit digest, crc32 would be suitable.
