### ISSUE TITLE
unable to detect stop of applications started via REST API

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#845]
My usecase is like:
 - start VM with -e "/cli/cli.so"
 - configure VM (setup environ, upload some on-the-fly generated files, mount NFS)
 - start myapp.so via REST API
 - wait on myapp.so to finish processing
 - terminate VM

After starting app, I'm not able to easily detect when it is done. It does write some strings to console, so it might be possible to grep for some magic strings (but that sounds so ugly).

The http-server will return immediately after calling osv::run https://github.com/cloudius-systems/osv/blob/master/modules/httpserver/api/app.cc#L39. We cannot just delay return from HTTP call until app is done:
 - http-server is single threaded/can process only one request at time, so that would block all other users.
 - if app executes for long time, the TCP connection would be dropped due to inactivity. 

Possible solution would be to return an identifier/handle instead of empty string, so that caller would be able to later check status of corresponding app. Handler could be just a thread id of thread running app's main().  

Are there better ideas?

**Comment by nyh** [comment]
In your setup, can the VM itself decide what it needs to do (by mounting something, downloading a file, etc.) - or does it need to wait for instructions initiated by you manually (or some unsolicited instructions from a central machine)?

If it's the former, and all you need is to shut down after the application finishes, we don't need to change anything because the existing code already waits for the httpserver-started applications before shutting down (that's what caused issue #843). So we can:

1.  Start httpserver in the background (put httpserver, not httpserver.fg, in the image=... list).
2. Start your configuration program in the foreground, and it will mount things, download things, and start a new application (via REST API if you prefer that) and then exit.
3. The shutdown code will now wait for that new application to finish - and when it does, it will shut down immediately.

Your proposal is still useful if some remote machine truely needs to learn abut this shutdown, to retrieve the exit code, or something like that.

**Comment by justinc1** [comment]
My case is "the former" - central machine/script starts mpirun, and after mpirun is finished, the real work is done.

But there were complains when VM kindly shut down after mpirun finished - in some cases user wanted to examine the VM (to download some files, to check dmesg/console log etc). So I had to drop that part.

Indeed, assuming that VM shutdown means you program finished processing - it is quite optimistic. Say ouf-of-memory occurs. Or say you have occasional crash.
