### ISSUE TITLE
SIOCGIFFLAGS, IFF_SLAVE incorrectly set on xen

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#862]
We noticed that when running openmpi, interface status is queried via ioctl SIOCGIFFLAGS, adn IFF_SLAVE is set. This does not happen on KVM, but it does on AWS and on xenserver too.

Code demonstrating bug was sent to mail list - https://groups.google.com/forum/#!topic/osv-dev/ZWXOwXzzsOU.

@nyh already commented

> We have IFF_SLAVE and IFF_SIMPLEX translate to the same bit (0x800). And then, in bsd/sys/dev/xen/netfront/netfront.cc we put:
> 
> bsd/sys/dev/xen/netfront/netfront.cc:        ifp->if_flags = IFF_BROADCAST | IFF_SIMPLEX | IFF_MULTICAST;

**Comment by nyh** [comment]
The bits which Linux applications expect are in /usr/include/net/if.h (or in OSv, include/api/net/if.h)
But the bits the internal BSD-based network stack uses are defined in bsbsd/sys/net/if.h.
Those are not the same bits, as @justinc1 noticed.

So, in bsd/sys/compat/linux/linux_ioctl.cc in case SIOCGIFFLAGS, we already call a function linux_gifflags() to translate the flags from the internal BSD bits to the Linux bits.
But it appears that this function doesn't do all the necessary translations. In particular it needs to remove the IFF_SIMPLEX  in particular it needs to remove the IFF_SIMPLEX bit  because it doesn't exist in Linux.

While we're at it, we should look at **all** the BSD bits (from include/api/net/if.h) and consider for each one whether it exists in Linux, if it doesn't, remove it in linux_giflags(), and if it does check if it's the same bit position.
