### ISSUE TITLE
Any reasons why this shouldn't work on ARM?

### ISSUE THREAD

**Issue by jaromil** [cloudius-systems/osv#875]
Hi there, I'm involved in another EU/H2020 funded project <https://decodeproject.eu> and now considering also OSv as a component. 

I well understand the presence of Intel in the Mikelangelo consortium somehow drives the development efforts to support that platform.... but do you see any problems why OSv wouldn't run also on ARM?

I'm asking for a wet finger estimation, since I found no information yet in the documentation.
OTOH I can well imagine this will run well on ARM and, say, Zulu JRE?

**Comment by dorlaor** [comment]
There is an ARM port but you'll need to check its state.
Zulu (on x86) was ported as well

**Comment by nyh** [comment]
Hi @jaromil since you asked here, I'll answer here but next time please use the OSv mailing list (osv-dev@googlegroups.com), not this bug tracker, for general discussion that does not related to any specific OSv bug, and let's use the mailing list also for followup discussion.

OSv indeed started supporting only x86_64 processors (Intel and AMD) and their typical ecosystem (hypervisors, drivers, etc.). But OSv was actually ported to 64-bit ARM ("aarch64") by two separate groups, one group was running it on a KVM hypervisor (which was itself ported to aarch64), and the second group was running OSv on the Xen hypervisor. Both are already in the OSv main branch, and apparently both do work. However, given that I haven't actually run the ARM port myself, I can't comment as to the readiness or stableness of the 64-bit ARM support, so I would recommend that you try it out yourself, and/or ask people on the mailing list about its state or how to try it.

Since you asked for an estimate, I'd say that even if OSv does not run out-of-the-box on 64-bit ARM today, I think it will take a fairly minor effort to get it to run, because most if not all of the pieces are already there, and people have already successfully used them. 

Zulu JRE does work on OSv, see for example apps/openjdk8/openjdk8-zulu-*. Again, I have never tried this myself so I suggest that you ask questions about this on the OSv mailing list.

And finally, yes, OSv is used in the MIKELANGELO H2020 project. However, Intel is not at all involved in the hardware aspect of this project, and was not the reason we started with Intel (or AMD) processors. The only reason we did that is that when we started - and still today - most of the cloud ecosystem used these processors. If you'd like to pick up OSv in your own H2020 project, I'm sure we in MIKELANGELO will be glad to help you get started.

**Comment by jaromil** [comment]
thanks @nyh for your answer! I'll plan some experiments (but will take some time, as we don't yet have arm64 builds in our CI, see https://files.devuan.org/devuan_jessie/embedded/) and eventually follow up via the mailinglist, sorry to confuse the channels of communications. Keep up the good work!
