### ISSUE TITLE
Latest Java 9 GA release does not work on OSv

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#912]
The GA release of JDK 9 has introduced some last minute directory layout changes that affected location of libjvm.so and causes java.so fail on startup with following output:

java.so: Starting JVM app using: io/osv/nonisolated/RunNonIsolatedJvmApp
terminate called after throwing an instance of 'std::runtime_error'
  what():  symbol not found JNI_GetDefaultJavaVMInitArgs
Aborted

[backtrace]
0x00000000004895cc <__gnu_cxx::__verbose_terminate_handler()+364>
0x0000000000ae84bf <???+11437247>

Up until Java 9 GA (including Java 9 EA) the location of libjvm.so was - **/usr/lib/jvm/jre/lib/amd64/server/libjvm.so**. In Java 9 it is - **/usr/lib/jvm/jre/lib/server/libjvm.so**.

There are number of solutions of this problem. One could be to re-structure java 9 folder structure using symlinks to make it backwards compatible with prior versions. I tried this and it did not quite work plus Java 9 directory structure is very different any way and you can read more about it [here](https://issues.jenkins-ci.org/browse/JENKINS-25993) and [here](https://www.journaldev.com/13106/java-9-modules).

So I think the best option is to create yet another module called java9-base or java9-cmd that would be almost identical to java-non-isolated and pass the path to libjvm.so as -D compiler parameter to java.cc to generate java 9 specific java.so. Alternatively all that logic could be in apps/java9-base or something but I am not sure it would work given java sources are in modules/java-base. Also java 9 makes possible to build custom JREs tailored to specific app by using jlink too which should be part of logic in apps/openjdk9-java-base. 

Yet another option would be to pass libjvm.so location as a runtime parameter to java.so but it would complicate java.cc logic quite a bit - for example it would need to filter out this new path parameter and make sure it is not passed to JNI_CreateJavaVM. So I still think the former one is superior.

Related question: how should we change the build system logic around java 9 to make it possible to pass custom set of JRE modules to jlink tool which constructs JRE?

**Comment by nyh** [comment]
If the libjvm.so location was the only difference, I don't think we need a new version of it. java.cc has code which looks like
```c++
#define JVM_PATH         "/usr/lib/jvm/jre/lib/amd64/server/libjvm.so"
    auto jvm_so = prog->get_library(JVM_PATH);
```
It should be very easy to have two of these paths, and if the first one doesn't work, try the second one. It doesn't have to be a general parameter like you suggested - we can just try both options, one will work for Java 7 and 8, the other for java 9.

Another alternative, is to create /usr/lib/jvm/jre/lib/amd64/server/libjvm.so as a symlink to  /usr/lib/jvm/jre/lib/server/libjvm.so.  But you said you tried this (this second alternative) but it didn't work because the directory structure changed - I didn't understand why that matters... Other than JVM_PATH, where does java.cc care about the structure of the JRE directories?
