### ISSUE TITLE
realpath dependency not installed on ubuntu 14.04

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#946]
I was trying to compile on an old ubuntu 14.04 VM, and got:
```
scripts/build mode=debug image=cli -j8
  APPEND_TO_MANIFEST api_app
  APPEND_TO_MANIFEST api_os
  APPEND_TO_MANIFEST api_env
/bin/sh: 1: realpath: not found
```

**Comment by nyh** [comment]
We could fairly easily add "realpath" to `scripts/setup.py`, but I think there are two other even better solutions. One is to use "readlink" (perhaps readlink -f) instead of realpath. We already did this change in the past in commit 769ea7d5a0de6d3d015443936c11fb7850d9ba6a, where we noted that "readlink" is installed by default everywhere, and is more standard (Ubuntu has a different "realpath" implementation than Fedora, for example).
Perhaps an even better option is not to use realpath at all, if it's not really needed. A simple grep yields the following uses:
```
modules/httpserver-api/Makefile:	echo "/usr/mgmt/plugins/libhttpserver-$(1).so: `realpath libhttpserver-$(1).so`" > _usr_$(1).manifest
modules/lua/Makefile:	$(eval PREFIX=$(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))
```
The first one is unnecessary - pwd should have worked just as well as realpath. In the second one, I'm not  even sure what this is trying to do, I'm guessing there's a much simpler way to do it with pwd or something - and if not, readlink -f could be used.

**Comment by justinc1** [comment]
https://ftp.gnu.org/old-gnu/Manuals/make/html_node/make_17.html. MAKEFILE_LIST is last-included (==current in our case) makefile, and all that "dirname $(realpath $(lastword $(MAKEFILE_LIST)" is another pwd. I wonder why was that used 

I guess it will be OK to use shell pwd (not /bin/pwd, /usr/bin/pwd) - it is already used in say:
./scripts/build:109:SRC=`pwd`

**Comment by nyh** [comment]
The directory holding the MAKEFILE may not be pwd if "make -C ..." was used. I don't know if it was. If you tried "scripts/build clean; scripts/build" after your patch, and it works, then I guess you did it correctly? :-)

By the way, make itself has the "abspath" function, e.g., `$(abspath $(lastword $(MAKEFILE_LIST)))`, that too could have been used instead of "realpath" if pwd is not an appropriate replacement (and I have no idea if it is).

**Comment by justinc1** [comment]
I was thinking about -C flag as possible reason for using dirname-realpath. I tired to compile lua only with "make -C osv/modules/lua/", and it did work, so I assumed that case is still working.
