### ISSUE TITLE
replace addPropertyChangeListener()/removePropertyChangeListener() on io/osv/jul/

### ISSUE THREAD

**Issue by geraldo-netto** [cloudius-systems/osv#953]
Dear @wkozaczuk / @nyh ,

I'm opening this ticket just as a note in the future for us to replace the following methods that were deprecated and removed on java9 [1]:
java.util.logging.LogManager.addPropertyChangeListener
java.util.logging.LogManager.removePropertyChangeListener
java.util.jar.Pack200.Packer.addPropertyChangeListener
java.util.jar.Pack200.Packer.removePropertyChangeListener
java.util.jar.Pack200.Unpacker.addPropertyChangeListener
java.util.jar.Pack200.Unpacker.removePropertyChangeListener

```
netto@besta01 ~/Desktop/osv/osv-2-crypt/modules/java-base/runjava-isolated/src/main/java/io/osv/jul $ grep -i 'addProperty\|removeProperty' *
IsolatingLogManager.java:    public void addPropertyChangeListener(PropertyChangeListener l) throws SecurityException {
IsolatingLogManager.java:        getDelegate().addPropertyChangeListener(l);
IsolatingLogManager.java:    public void removePropertyChangeListener(PropertyChangeListener l) throws SecurityException {
IsolatingLogManager.java:        getDelegate().removePropertyChangeListener(l);
LogManagerWrapper.java:            manager.addPropertyChangeListener(new PropertyChangeListener() {
```

[1] https://docs.oracle.com/javase/9/migrate/JSMIG.pdf

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
Dear @geraldo-netto,

I am not sure if removing these obsolete methods/classes is the correct solution. Indeed those method are gone starting with Java 9.

To run Java apps OSv provides bootstrapping code which is a mixture of C++ (java.cc) and Java. The point of the java.cc app is to initialize JVM runtime based on passed in JVM parameters and start specified user java app using "class with static main method" way or -jar way with user packaged JAR app bundle (things may have changed with Java 10). However instead of directly passing user class name (or jar), java.cc actually delegates executing user code to OSv provided tiny java bootstrapping code (I will skip reasons why -> should go into wiki page). There are two flavors of this bootstrapping java code - **isolated** (older and more complicated) and **non-isolated** (newer and simpler) mode. The point of the isolated mode is to allow running **multiple** Java apps on single JVM with pseudo-isolation (separate hierarchy of classloaders and loggers) and that is why it uses some of the methods which were removed from Java 9 and on. On other hand non-isolated mode allows to run single app (no isolation needed) and does not use any of these deprecated methods.

Please see following commits for details:
- https://github.com/cloudius-systems/osv/commit/785e57e60969e25c19c87ad1b922ad9b66428c0e
- https://github.com/cloudius-systems/osv/commit/bee9421617a4f812b49ada00e83127bb112f4499
- https://github.com/cloudius-systems/osv/commit/f0bb5c24d5ba00a7418b1bf5a46043ce2c12eae5 - this one talks about mechanics of building isolated vs non-isolated mode Java images

To make long story short the isolated mode is dead end passed Java 8 (also does not work with Java 8 compact profiles) unless we rework that bootstrapping code to make it work on Java 9 and late versions. But then we would probably have to have 2 version of this code - pre-Java 9 and Java 9 and higher. Also in my opinion unikernels and OSv in particular are intended to run single apps (microservices or similar) so personally I would not invest our time into making this work on Java 9. The non-isolated mode is simpler and does not have any of this compatibility issues (I have not tested it on Java 10 so who knows). Right now the isolated mode is the default one and I would advocate that at some point we change it to non-isolated one. However this might cause upstream changes in projects like Mikelangelo capstan and Unik.

Having said all this I think we should make sure to keep the OSv build process compile OSv bootstrapping java code to Java 7 bytecode version so that it can be used to run user apps compiled to any version of bytecode (Java 7 or up) with caveats of isolated vs non-isolated mode.

I think this issue can be closed once we have new/updated Wiki page about how to deploy JVM apps on OSv which describes all these gotchas.

PS. It would be nice to test Java 10 - it was just released 1 week ago.

**Comment by nyh** [comment]
On the mailing list I suggested two options without changing the Java code, maybe one of them will work?
1. Use "-source 7" or find the older compiler during the build. I'm not sure the former works (do they have Java 7 classes in Java 9?) but the latter should, if we manage to find it (perhaps by running "alternatives"?)
2. Make sure that important modules like "tests" require "java-nonisolated" instead of "java", and "java-nonisolated" works on Java 9 too (I hope...).

**Comment by geraldo-netto** [comment]
Dear @wkozaczuk / @nyh ,

How are you doing?

Today I took some time to check the non-isolated mode and so far, things look good OpenJDK7 and OpenJDK8 seems to work flawlessly

What do you think about changing the default from isolated to non-isolated?
That way we make OSv compatible with newer java apps automatically and we don't need to check the java unit tests (just change the module.py file in a few places which is cleaner and much less invasive)

Another thing that I think it's important to mention is that OpenJDK7 is unsupported,
latest release from 2011:
(http://openjdk.java.net/projects/jdk7/calendar/)
M1 | 2009/01/02 – 2009/01/08 | b42
...
M13 | 2011/05/27 – 2011/06/02 | b145

Do you think it's a good idea to set OpenJDK8 as the default?


Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
I guess we are in full agreement then. I will prepare the patch then.

**Comment by geraldo-netto** [comment]
Hello @wkozaczuk / @nyh ,

I did a quick patch (attached as txt file) for it based on my tests from y'day
I have tested with some java apps including apache derby and tomcat
One thing that I'm not sure is if we need to change any other module
(In my tests it worked just with 2 changes - java/module.py and java-cmd/module.py)

[0001-java-set_non_isolated_mode.txt](https://github.com/cloudius-systems/osv/files/2134238/0001-java-set_non_isolated_mode.txt)

Hope it helps! :)

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
@geraldo-netto Given we changed build process to use the non-isolated mode by default which fixes this issue, can we close it?
