### ISSUE TITLE
Be more selective on symbols exported from the kernel

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#97]
Right now, we export all symbols from the kernel, and they can all be used by shared objects.

This has a number of negative implications.

First is of course that applications can accidentally use kernel objects which we never intended to expose.

The second is that all these symbols (and C++ symbols have L-O-N-G names...) appear in the .dynstr and .dynsym sections of the kernel (loader-stripped.elf), which amounts to almost 1MB.

We should consider only exporting some of the symbols, not all of them.

**Comment by wkozaczuk** [comment]
Here is what I propose to identify symbols that need to stay exported/public from kernel (somewhat inspired by trying to solve #1040) and use this code in core/elf.cc as a basis:

```
    static const auto supplied_modules = {
          "libresolv.so.2",
          "libc.so.6",
          "libm.so.6",
#ifdef __x86_64__
          "ld-linux-x86-64.so.2",
          "libboost_system.so.1.55.0",
          "libboost_program_options.so.1.55.0",
#endif /* __x86_64__ */
#ifdef __aarch64__
          "ld-linux-aarch64.so.1",
          "libboost_system-mt.so.1.55.0",
          "libboost_program_options-mt.so.1.55.0",
#endif /* __aarch64__ */
          "libpthread.so.0",
          "libdl.so.2",
          "librt.so.1",
          "libstdc++.so.6",
          "libaio.so.1",
          "libxenstore.so.3.0",
          "libcrypt.so.1",
    };
```

1. Find the list of exported symbols by Linux equivalent (```nm -CD /lib/x86_64-linux-gnu/libc.so.6```) for each library (except the boost ones which we plan to hide anyway).
2. Find the intersection between the sum of the above and symbols exported by OSv (```nm -CD build/release/loader-stripped.elf```).
3. Use the result of the 2 to add ```attribute ((visibility ("default")))``` in all identified places (provided all sources are compiled with ```-fvisibility=hidden```. 

The step 3 might be pretty tedious but maybe we can ease the pain by compiling groups of source files (all directories as is) like musl with NO ```-fvisibility=hidden```.

**Comment by wkozaczuk** [comment]
Based on this take from [the GCC Visibility article](https://gcc.gnu.org/wiki/Visibility):

`To aid you converting old code to use the new system, GCC now supports also a #pragma GCC visibility command:


extern void foo(int);
#pragma GCC visibility push(hidden)
extern void someprivatefunct(int);
#pragma GCC visibility pop
#pragma GCC visibility is stronger than -fvisibility; **it affects extern declarations as well**. -fvisibility only affects definitions, so that existing code can be recompiled with minimal changes. This is more true for C than C++; C++ interfaces tend use classes, which are affected by -fvisibility.'`

it seems we should be able to put ```attribute ((visibility ("default")))``` in some kind of master header file with externs that would be included everywhere. That way we might not need to manually modify hundreds of files, no?

**Comment by nyh** [comment]
I think we don't have to play (just yet) with the visibility of all the OSV symbols, and could perhaps just surround the #include of boost headers with a pragma push visibility hidden. I can't check this now, I'm standing in line in Zurich airport. So good luck :-)

**Comment by wkozaczuk** [comment]
Some critical code snippets intended to make it easier to understand my proposal:
- [exported libraries](https://github.com/cloudius-systems/osv/blob/a2128797e43d793b44ffd0d406ae1742923d237b/core/elf.cc#L1287-L1317) - all C symbols provided to regular Linux apps (vs internal apps like cpiod) belong to one of the libraries listed as part of the `supplied_modules` array below
```C++
    // Our kernel already supplies the features of a bunch of traditional
    // shared libraries:
    static const auto supplied_modules = {
          "libresolv.so.2",
          "libc.so.6",
          "libm.so.6",
#ifdef __x86_64__
          "ld-linux-x86-64.so.2",
          "libc.musl-x86_64.so.1",
          // As noted in issue #1040 Boost version 1.69.0 and above is
          // compiled with hidden visibility, so even if the kernel uses
          // this library, it will not be visible for the application and
          // it will need to load its own version of this library.
#if BOOST_VERSION < 106900
          "libboost_system.so.1.55.0",
#endif
#endif /* __x86_64__ */
#ifdef __aarch64__
          "ld-linux-aarch64.so.1",
#if BOOST_VERSION < 106900
          "libboost_system-mt.so.1.55.0",
#endif
#endif /* __aarch64__ */
          "libpthread.so.0",
          "libdl.so.2",
          "librt.so.1",
          "libstdc++.so.6",
          "libaio.so.1",
          "libxenstore.so.3.0",
          "libcrypt.so.1",
    };
```
- [linked static libraries](https://github.com/cloudius-systems/osv/blob/a2128797e43d793b44ffd0d406ae1742923d237b/Makefile#L1855-L1882) - all non-hidden symbols in the libraries linked statically as part of the kernel are also implicitly exposed; please note that 3 libraries - `libstdc++.a`, `libgcc_eh.a` and `boost-libs` are linked `--whole-archive` which means all public symbols (whether used or not) from those libraries are implicitly exposed as well.
```make
$(out)/kernel.elf: $(stage1_targets) arch/$(arch)/loader.ld $(out)/empty_bootfs.o $(loader_options_dep)
	$(call quiet, $(LD) -o $@ --defsym=OSV_KERNEL_BASE=$(kernel_base) \
	    --defsym=OSV_KERNEL_VM_BASE=$(kernel_vm_base) --defsym=OSV_KERNEL_VM_SHIFT=$(kernel_vm_shift) \
		-Bdynamic --export-dynamic --eh-frame-hdr --enable-new-dtags -L$(out)/arch/$(arch) \
	    $(^:%.ld=-T %.ld) \
	    --whole-archive \
	      $(libstdc++.a) $(libgcc_eh.a) \
	      $(boost-libs) \
	    --no-whole-archive $(libgcc.a), \
		LINK kernel.elf)
```

There are around 17K symbols

Here is a fairly comprehensive recipe of how we can hide most symbols and expose only those needed. The recipe makes following assumption. 

**To be continued**

**Comment by wkozaczuk** [comment]
I believe we can close this issue as it has been addressed by [this commit](https://github.com/cloudius-systems/osv/commit/af2d371a61f6ab1eb5a066a0c3e93230faf6611c) and the related ones that allow us to build the kernel with most symbols hidden according to the plan outlined in the previous comment. I have also added a [new issue](https://github.com/cloudius-systems/osv/issues/1186) to address outstanding functionality.
Please note that by default the kernel still exposes all symbols including standard C++library ones, and in order to hide symbols one has to build the kernel with the ` conf_hide_symbols=1` option as below:
```
./scripts/build image=native-example fs=rofs conf_hide_symbols=1 -j$(nproc)
```
