### ISSUE TITLE
Tcp server using epoll stops accepting new connections after first request

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#974]
This issue has been observed when testing golang-httpserver app which would hang after first connect and stop accepting following requests (for example from curl). However because of the nature of the underlying bug it should be impacting any app using [epoll](http://man7.org/linux/man-pages/man7/epoll.7.html) API with sockets.

The core of the epoll API in OSv is implemented in [core/epoll.cc](https://github.com/cloudius-systems/osv/blob/master/core/epoll.cc) and for some key aspects it is based on poll() implementation. More specifically in key points epoll_file methods invoke poll() method on file object (could be an instance of socket_file, vfs_file or other subclass of file). The key element of epoll API are flags passed in to **epoll_add**/**epoll_mod** functions that specify what kind of events user is interested receiving for specific file descriptor. Most of the E-flags (like EPOLLIN) correspond to poll API flags (EPOLLIN=POLLIN) however at least 2 of them are specific to epoll:
- EPOLLONESHOT - makes specific type of events (for example EPOLLIN) be reported only once; all the implementation of this aspect is part of core/epoll.cc 
- EPOLLET - specifies edge-triggered behavior (read 'Level-triggered and edge-triggered' section of epoll Linux manual); most of the implementation of this aspect is part of core/epoll.cc however for **socket files it relies on epoll-specific logic in [uipc_socket.cc: sopoll_generic_locked()](https://github.com/cloudius-systems/osv/blob/master/bsd/sys/kern/uipc_socket.cc#L3193)** to manipulate state of corresponding socket object to make it ready to receive or send more data. This means that EPOLLET flag has to be passed in all the way there through socket_file::poll() method used by epoll.

The commit https://github.com/cloudius-systems/osv/commit/9eb6f2e38dc0103bd0d64a17221e2cc59b8cb138 related to issue #971 to filter out EPOLL* flags passed to poll() methods was based on the assumption that poll() methods would NOT know what to do with the epoll specific flags (EPOLLET and EPOLLONESHOT) and remove those in events_epoll_to_poll() function. This would be correct if that assumption was true but as you can see from the paragraph above it is not as sopoll_generic_locked() relies on EPOLLET flags (if epoll used) to function properly.

The likely solution is to tweak events_epoll_to_poll() to make it NOT remove EPOLLET and ideally define two sets of flags instead of single SUPPORTED_EVENTS - one of epoll-2-poll and another for poll-2-epoll. Please also note that existing tst-epoll.cc does not test sockets so corresponding test would need to be added to the test.

**Comment by nyh** [comment]
Hi @wkozaczuk, sorry about this regression. I just sent a patch to the mailing list, "epoll: fix regression in EPOLLET on network sockets", can you please test it?
Your explanation above nailed the problem: I wanted to filter out EPOLLET (and EPOLLONESHOT) because traditionally poll() shouldn't get those bits - and poll_no_poll() used it crash if getting them (it no longer does). But we can't filter out EPOLLET - because the socket implementation of poll() - sopoll_generic_locked() - needs this bit, for reasons explained in commit d41d748f89cf6e47820e8585cef6eedb837c05be.
So the simple solution is not to filter out this bit.  This is what I did in the patch I just sent.
I could also avoid this filtering completely (like in your change to "return e;"), but I thought it's really cleaner not to pass EPOLLONESHOT to the poll() methods.
